"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import {
  ArrowLeft,
  Users,
  Zap,
  Star,
  TrendingUp,
  Search,
  ChevronDown,
  ChevronUp,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  ExternalLink,
  RefreshCw,
  Clock,
  Target,
  Archive,
  FileText,
  MessageSquare,
  Download,
  Upload,
  Loader2,
  X,
  Trash2,
} from "lucide-react";
import jsPDF from "jspdf";

// ─── Types ────────────────────────────────────────────────────────────────────

type ScreeningStatus = "pending" | "processing" | "completed" | "failed";
type CandidateStatus = "new" | "reviewing" | "shortlisted" | "rejected";

interface BlindSession {
  id: string;
  name: string;
  description: string | null;
  status: "active" | "archived";
  cv_count: number;
  created_at: string;
}

interface Candidate {
  id: string;
  candidate_name: string;
  candidate_email: string;
  cv_url: string;
  status: CandidateStatus;
  screening_status: ScreeningStatus;
  ai_score: number | null;
  ai_summary: string | null;
  ai_strengths: string[] | null;
  ai_red_flags: string[] | null;
  ai_justification: string | null;
  interview_questions: string[] | null;
  applied_at: string;
  ai_recommendation: "shortlist" | "consider" | "reject" | null;
}

// ─── Config ───────────────────────────────────────────────────────────────────

const scoreColor = (score: number | null) => {
  if (!score)
    return { color: "#94a3b8", bg: "rgba(148,163,184,0.1)", label: "—" };
  if (score >= 80)
    return { color: "#16a34a", bg: "rgba(34,197,94,0.1)", label: "Strong" };
  if (score >= 60)
    return { color: "#d97706", bg: "rgba(245,158,11,0.1)", label: "Good" };
  if (score >= 40)
    return { color: "#ea580c", bg: "rgba(234,88,12,0.1)", label: "Fair" };
  return { color: "#ef4444", bg: "rgba(239,68,68,0.1)", label: "Weak" };
};

const statusConfig: Record<
  CandidateStatus,
  { label: string; color: string; bg: string }
> = {
  new: { label: "New", color: "#3b82f6", bg: "rgba(59,130,246,0.1)" },
  reviewing: {
    label: "Reviewing",
    color: "#d97706",
    bg: "rgba(245,158,11,0.1)",
  },
  shortlisted: {
    label: "Shortlisted",
    color: "#16a34a",
    bg: "rgba(34,197,94,0.1)",
  },
  rejected: { label: "Rejected", color: "#ef4444", bg: "rgba(239,68,68,0.1)" },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function timeAgo(dateStr: string) {
  const diff = Date.now() - new Date(dateStr).getTime();
  const days = Math.floor(diff / 86400000);
  const hours = Math.floor(diff / 3600000);
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  if (hours < 24) return `${hours}h ago`;
  if (days < 30) return `${days}d ago`;
  return new Date(dateStr).toLocaleDateString("en-PK", {
    day: "numeric",
    month: "short",
  });
}

function initials(name: string) {
  return name
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}

const AVATAR_COLORS = [
  ["#7C3AED", "#ede9fe"],
  ["#2563eb", "#dbeafe"],
  ["#16a34a", "#dcfce7"],
  ["#d97706", "#fef3c7"],
  ["#db2777", "#fce7f3"],
  ["#0891b2", "#cffafe"],
];
function avatarColor(name: string) {
  return AVATAR_COLORS[name.charCodeAt(0) % AVATAR_COLORS.length];
}

// ─── Download interview questions as .txt ─────────────────────────────────────
// Generates a plain text file HR can print or use in interviews.

function downloadInterviewQuestions(candidate: Candidate, sessionName: string) {
  const questions = candidate.interview_questions ?? [];
  const date = new Date().toLocaleDateString("en-PK", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  // ── Header background bar ──
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, pageW, 28, "F");

  // ── Header text ──
  doc.setFontSize(15).setFont("helvetica", "bold").setTextColor(255, 255, 255);
  doc.text("Interview Questions", 14, 17);
  doc.setFontSize(9).setFont("helvetica", "normal").setTextColor(220, 210, 255);
  doc.text("Generated by SahiScreen AI", pageW - 14, 17, { align: "right" });

  // ── Meta info box ──
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 34, pageW - 28, 26, 3, 3, "FD");

  doc.setFontSize(9).setFont("helvetica", "bold").setTextColor(100, 116, 139);
  doc.text("CANDIDATE", 20, 43);
  doc.text("SESSION", 85, 43);
  doc.text("DATE", 155, 43);

  doc.setFontSize(10).setFont("helvetica", "bold").setTextColor(15, 23, 42);
  doc.text(candidate.candidate_name, 20, 52);
  doc.text(sessionName, 85, 52, { maxWidth: 60 });
  doc.text(date, 155, 52, { maxWidth: 40 });

  // ── Divider ──
  doc.setDrawColor(124, 58, 237);
  doc.setLineWidth(0.5);
  doc.line(14, 66, pageW - 14, 66);

  // ── Questions ──
  let y = 76;

  questions.forEach((q, i) => {
    const lines = doc.splitTextToSize(q, pageW - 50);
    const blockH = lines.length * 6 + 10;

    if (y + blockH > pageH - 24) {
      doc.addPage();

      // Repeat header on new page
      doc.setFillColor(124, 58, 237);
      doc.rect(0, 0, pageW, 18, "F");
      doc
        .setFontSize(9)
        .setFont("helvetica", "bold")
        .setTextColor(255, 255, 255);
      doc.text("Interview Questions — " + candidate.candidate_name, 14, 12);

      y = 28;
    }

    // Number badge background
    doc.setFillColor(124, 58, 237);
    doc.roundedRect(14, y - 4, 8, 8, 1.5, 1.5, "F");

    // Number
    doc.setFontSize(8).setFont("helvetica", "bold").setTextColor(255, 255, 255);
    doc.text(String(i + 1), 18, y + 1.5, { align: "center" });

    // Question text
    doc
      .setFontSize(10.5)
      .setFont("helvetica", "normal")
      .setTextColor(55, 65, 81);
    doc.text(lines, 28, y + 1);

    y += blockH;

    // Light separator between questions
    if (i < questions.length - 1) {
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.3);
      doc.line(28, y - 2, pageW - 14, y - 2);
    }
  });

  // ── Footer ──
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);

    doc.setFillColor(248, 250, 252);
    doc.rect(0, pageH - 14, pageW, 14, "F");
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(0, pageH - 14, pageW, pageH - 14);

    doc.setFontSize(8).setFont("helvetica", "bold").setTextColor(124, 58, 237);
    doc.text("SahiScreen", 14, pageH - 5);

    doc.setFont("helvetica", "normal").setTextColor(100, 116, 139);
    doc.text("Trustable", 35, pageH - 5);

    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${p} of ${totalPages}`, pageW - 14, pageH - 5, {
      align: "right",
    });
  }

  doc.save(
    `Interview_Questions_${candidate.candidate_name.replace(/\s+/g, "_")}.pdf`,
  );
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function BlindScreeningDetailPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();

  const [session, setSession] = useState<BlindSession | null>(null);
  const [candidates, setCandidates] = useState<Candidate[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [scoreFilter, setScoreFilter] = useState<
    "all" | "strong" | "good" | "fair" | "weak"
  >("all");
  const [sortBy, setSortBy] = useState<"score" | "date">("score");
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [updatingIds, setUpdatingIds] = useState<Set<string>>(new Set());
  const [archiving, setArchiving] = useState(false);
  const [uploadPanelOpen, setUploadPanelOpen] = useState(false);
  const [uploadFiles, setUploadFiles] = useState<
    Array<{
      id: string;
      name: string;
      size: number;
      status: "pending" | "uploading" | "done" | "error";
      error?: string;
    }>
  >([]);
  const [uploadDragging, setUploadDragging] = useState(false);
  const [uploadTriggering, setUploadTriggering] = useState(false);
  const uploadFileInputRef = useRef<HTMLInputElement>(null);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [deleteConfirmText, setDeleteConfirmText] = useState("");
  const [deleting, setDeleting] = useState(false);

  const lock = (id: string) => setUpdatingIds((p) => new Set(p).add(id));
  const unlock = (id: string) =>
    setUpdatingIds((p) => {
      const n = new Set(p);
      n.delete(id);
      return n;
    });

  // ── Upload more CVs helpers ───────────────────────────────────────────────

  const toBase64Upload = (file: File): Promise<string> =>
    new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve((reader.result as string).split(",")[1]);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });

  const uploadOneFile = async (file: File, fileId: string) => {
    setUploadFiles((prev) =>
      prev.map((f) => (f.id === fileId ? { ...f, status: "uploading" } : f)),
    );

    try {
      const base64 = await toBase64Upload(file);
      const res = await fetch(`/api/blind-screening/${id}/upload`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          file_base64: base64,
          original_filename: file.name,
          file_type: file.type,
          file_size_kb: Math.round(file.size / 1024),
        }),
      });

      const data = await res.json();
      if (!res.ok) {
        setUploadFiles((prev) =>
          prev.map((f) =>
            f.id === fileId
              ? { ...f, status: "error", error: data.error ?? "Upload failed" }
              : f,
          ),
        );
      } else {
        setUploadFiles((prev) =>
          prev.map((f) => (f.id === fileId ? { ...f, status: "done" } : f)),
        );
      }
    } catch {
      setUploadFiles((prev) =>
        prev.map((f) =>
          f.id === fileId
            ? { ...f, status: "error", error: "Network error" }
            : f,
        ),
      );
    }
  };

  const addUploadFiles = async (newFiles: FileList | File[]) => {
    const arr = Array.from(newFiles).filter(
      (f) =>
        f.type === "application/pdf" ||
        f.name.endsWith(".pdf") ||
        f.name.endsWith(".docx"),
    );
    const entries = arr.map((f) => ({
      id: crypto.randomUUID(),
      name: f.name,
      size: f.size,
      status: "pending" as const,
    }));
    setUploadFiles((prev) => [...prev, ...entries]);
    for (let i = 0; i < arr.length; i++) {
      await uploadOneFile(arr[i], entries[i].id);
    }
  };

  const handleUploadDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setUploadDragging(false);
    addUploadFiles(e.dataTransfer.files);
  };

  const handleScreenNewCVs = async () => {
    setUploadTriggering(true);
    try {
      await fetch(`/api/blind-screening/${id}/trigger`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      setUploadFiles([]);
      setUploadPanelOpen(false);
      fetchData(true);
    } catch {
      // silent — polling will catch results
    } finally {
      setUploadTriggering(false);
    }
  };
  const handleDeleteSession = async () => {
    if (deleteConfirmText !== "DELETE") return;
    setDeleting(true);
    try {
      const res = await fetch(`/api/blind-screening/${id}`, {
        method: "DELETE",
      });
      if (res.ok) {
        router.push("/dashboard/screening");
      }
    } catch {
      // silent
    } finally {
      setDeleting(false);
    }
  };
  const fetchData = useCallback(
    async (silent = false) => {
      if (!silent) setLoading(true);
      try {
        const res = await fetch(`/api/blind-screening/${id}`);
        if (!res.ok) return;
        const json = await res.json();
        if (json.session) setSession(json.session);
        if (json.candidates) {
          setCandidates(json.candidates);
        }
      } catch {
        /* silent */
      } finally {
        if (!silent) setLoading(false);
      }
    },
    [id],
  );

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // Polling while CVs are processing
  useEffect(() => {
    const hasProcessing = candidates.some(
      (c) =>
        c.screening_status === "processing" || c.screening_status === "pending",
    );
    if (!hasProcessing) return;
    const interval = setInterval(() => fetchData(true), 8000);
    return () => clearInterval(interval);
  }, [candidates, fetchData]);

  const handleStatusChange = async (
    candidateId: string,
    status: CandidateStatus,
  ) => {
    if (updatingIds.has(candidateId)) return;
    const prev = candidates;
    lock(candidateId);
    setCandidates((p) =>
      p.map((c) => (c.id === candidateId ? { ...c, status } : c)),
    );

    try {
      const res = await fetch(`/api/candidates/${candidateId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status, hr_notes: "" }),
      });
      if (!res.ok) setCandidates(prev);
      const err = await res.json();
      console.error("Status update failed:", err);
    } catch {
      setCandidates(prev);
    } finally {
      unlock(candidateId);
    }
  };

  const handleArchive = async () => {
    if (!session || archiving) return;
    setArchiving(true);
    const res = await fetch(`/api/blind-screening/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        status: session.status === "active" ? "archived" : "active",
      }),
    });
    if (res.ok) {
      const data = await res.json();
      setSession(data.session);
    }
    setArchiving(false);
  };

  const filtered = candidates
    .filter((c) => {
      if (
        search &&
        !c.candidate_name.toLowerCase().includes(search.toLowerCase())
      )
        return false;
      if (scoreFilter !== "all") {
        const s = c.ai_score ?? 0;
        if (scoreFilter === "strong" && s < 80) return false;
        if (scoreFilter === "good" && (s < 60 || s >= 80)) return false;
        if (scoreFilter === "fair" && (s < 40 || s >= 60)) return false;
        if (scoreFilter === "weak" && s >= 40) return false;
      }
      return true;
    })
    .sort((a, b) =>
      sortBy === "score"
        ? (b.ai_score ?? -1) - (a.ai_score ?? -1)
        : new Date(b.applied_at).getTime() - new Date(a.applied_at).getTime(),
    );

  const screened = candidates.filter(
    (c) => c.screening_status === "completed",
  ).length;
  const shortlisted = candidates.filter(
    (c) => c.status === "shortlisted",
  ).length;
  const scoredCandidates = candidates.filter((c) => c.ai_score !== null);
  const avgScore =
    scoredCandidates.length > 0
      ? Math.round(
          scoredCandidates.reduce((s, c) => s + (c.ai_score ?? 0), 0) /
            scoredCandidates.length,
        )
      : null;

  if (loading)
    return (
      <div
        style={{ padding: 32, fontFamily: "'Plus Jakarta Sans',sans-serif" }}
      >
        {[1, 2, 3].map((i) => (
          <div
            key={i}
            style={{
              background: "#fff",
              border: "1px solid #e2e8f0",
              borderRadius: 14,
              padding: "18px 20px",
              display: "flex",
              gap: 16,
              alignItems: "center",
              marginBottom: 10,
            }}
          >
            <div
              style={{
                width: 44,
                height: 44,
                borderRadius: 12,
                flexShrink: 0,
                background:
                  "linear-gradient(90deg,#f1f5f9 25%,#e2e8f0 50%,#f1f5f9 75%)",
                backgroundSize: "800px 100%",
                animation: "shimmer 1.4s infinite",
              }}
            />
            <div
              style={{
                flex: 1,
                display: "flex",
                flexDirection: "column",
                gap: 8,
              }}
            >
              <div
                style={{
                  height: 14,
                  width: "35%",
                  borderRadius: 6,
                  background:
                    "linear-gradient(90deg,#f1f5f9 25%,#e2e8f0 50%,#f1f5f9 75%)",
                  backgroundSize: "800px 100%",
                  animation: "shimmer 1.4s infinite",
                }}
              />
              <div
                style={{
                  height: 11,
                  width: "55%",
                  borderRadius: 6,
                  background:
                    "linear-gradient(90deg,#f1f5f9 25%,#e2e8f0 50%,#f1f5f9 75%)",
                  backgroundSize: "800px 100%",
                  animation: "shimmer 1.4s infinite",
                }}
              />
            </div>
          </div>
        ))}
      </div>
    );

  if (!session)
    return (
      <div
        style={{
          padding: 32,
          textAlign: "center",
          fontFamily: "'Plus Jakarta Sans',sans-serif",
        }}
      >
        <div style={{ fontSize: 16, fontWeight: 700, color: "#0f172a" }}>
          Session not found
        </div>
        <Link
          href="/dashboard/screening"
          style={{
            color: "#7C3AED",
            fontSize: 13,
            marginTop: 8,
            display: "inline-block",
          }}
        >
          ← Back to Screening
        </Link>
      </div>
    );

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap');
        * { box-sizing: border-box; }
        .sd-page {
          min-height: 100%; background: #f8fafc;
          padding: 28px 32px 60px;
          font-family: 'Plus Jakarta Sans', sans-serif;
        }
        @keyframes fadeUp { from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)} }
        @keyframes shimmer { from{background-position:-400px 0}to{background-position:400px 0} }
        @keyframes spin { from{transform:rotate(0deg)}to{transform:rotate(360deg)} }
        .reveal{animation:fadeUp .38s cubic-bezier(.22,1,.36,1) both}
        .r1{animation-delay:.04s}.r2{animation-delay:.10s}
        .r3{animation-delay:.16s}.r4{animation-delay:.22s}
        .spinning{animation:spin 1.2s linear infinite}

        .back-link{display:inline-flex;align-items:center;gap:7px;font-size:13px;font-weight:600;color:#64748b;text-decoration:none;margin-bottom:18px;transition:color .18s}
        .back-link:hover{color:#7C3AED}

        .header-card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:22px 24px;margin-bottom:20px;display:flex;align-items:flex-start;gap:18px;flex-wrap:wrap}
        .header-icon{width:52px;height:52px;border-radius:14px;background:rgba(124,58,237,.1);display:flex;align-items:center;justify-content:center;flex-shrink:0}
        .header-info{flex:1;min-width:0}
        .header-title{font-size:20px;font-weight:800;color:#0f172a;letter-spacing:-.4px;margin-bottom:4px}
        .header-desc{font-size:13px;color:#64748b;margin-bottom:6px}
        .header-actions{display:flex;gap:10px;align-items:center;flex-shrink:0;flex-wrap:wrap}

        .btn-outline{display:flex;align-items:center;gap:7px;padding:9px 16px;border-radius:10px;border:1.5px solid #e2e8f0;background:#fff;font-size:13px;font-weight:600;color:#374151;cursor:pointer;transition:all .18s;white-space:nowrap;font-family:'Plus Jakarta Sans',sans-serif;text-decoration:none}
        .btn-outline:hover{border-color:#7C3AED;color:#7C3AED}

        .stats-row{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}
        .stat-mini{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px 18px;display:flex;align-items:center;gap:12px}
        .sm-icon{width:36px;height:36px;border-radius:10px;display:flex;align-items:center;justify-content:center;flex-shrink:0}
        .sm-val{font-size:20px;font-weight:800;color:#0f172a;letter-spacing:-.5px}
        .sm-lbl{font-size:11px;color:#64748b;font-weight:500;margin-top:1px}

        .toolbar{display:flex;align-items:center;gap:10px;margin-bottom:16px;flex-wrap:wrap}
        .search-wrap{position:relative;flex:1;min-width:180px;max-width:300px}
        .search-ico{position:absolute;left:11px;top:50%;transform:translateY(-50%);pointer-events:none}
        .search-inp{width:100%;padding:8px 12px 8px 34px;border:1.5px solid #e2e8f0;border-radius:10px;font-size:13px;font-family:'Plus Jakarta Sans',sans-serif;color:#0f172a;background:#fff;outline:none;transition:border-color .2s,box-shadow .2s}
        .search-inp::placeholder{color:#94a3b8}
        .search-inp:focus{border-color:#7C3AED;box-shadow:0 0 0 3px rgba(124,58,237,.08)}
        .sel-wrap{position:relative}
        .filter-sel{padding:8px 30px 8px 12px;border:1.5px solid #e2e8f0;border-radius:10px;font-size:12px;font-weight:600;font-family:'Plus Jakarta Sans',sans-serif;color:#374151;background:#fff;outline:none;cursor:pointer;appearance:none}
        .sel-arr{position:absolute;right:9px;top:50%;transform:translateY(-50%);pointer-events:none}
        .sort-btn{display:flex;align-items:center;gap:6px;padding:8px 14px;border:1.5px solid #e2e8f0;border-radius:10px;background:#fff;font-size:12px;font-weight:600;color:#374151;cursor:pointer;transition:all .18s;font-family:'Plus Jakarta Sans',sans-serif}
        .sort-btn.active{border-color:#7C3AED;color:#7C3AED;background:rgba(124,58,237,.06)}

        .candidate-card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;margin-bottom:10px;overflow:hidden;transition:box-shadow .2s,transform .18s}
        .candidate-card:hover{box-shadow:0 4px 20px rgba(0,0,0,.07);transform:translateY(-1px)}
        .candidate-row{display:flex;align-items:center;gap:14px;padding:14px 18px;cursor:default}
        .c-avatar{width:42px;height:42px;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:800;flex-shrink:0}
        .c-info{flex:1;min-width:0}
        .c-name{font-size:14px;font-weight:700;color:#0f172a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
        .c-meta{display:flex;align-items:center;gap:7px;margin-top:3px;flex-wrap:wrap}
        .c-meta-item{font-size:11px;color:#64748b;font-weight:500}
        .c-dot{width:3px;height:3px;border-radius:50%;background:#cbd5e1;flex-shrink:0}
        .score-wrap{display:flex;flex-direction:column;align-items:center;gap:3px;min-width:56px}
        .score-ring{width:48px;height:48px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:800;border:3px solid;flex-shrink:0}
        .score-label{font-size:10px;font-weight:700}
        .c-right{display:flex;align-items:center;gap:10px;flex-shrink:0}
        .c-status{font-size:11px;font-weight:600;padding:4px 10px;border-radius:20px;white-space:nowrap}
        .expand-btn{width:30px;height:30px;border-radius:8px;border:1.5px solid #e2e8f0;background:#fff;display:flex;align-items:center;justify-content:center;cursor:pointer;transition:border-color .2s}
        .expand-btn:hover{border-color:#7C3AED}

        .ai-panel{border-top:1px solid #f1f5f9;padding:18px 20px;background:linear-gradient(135deg,rgba(124,58,237,.02),rgba(91,33,182,.01));animation:fadeUp .28s cubic-bezier(.22,1,.36,1)}
        .ai-panel-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
        .ai-section-title{font-size:11px;font-weight:700;color:#7C3AED;text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px;display:flex;align-items:center;gap:6px}
        .ai-summary{font-size:13px;color:#374151;line-height:1.6;background:rgba(124,58,237,.04);border:1px solid rgba(124,58,237,.1);border-radius:10px;padding:12px 14px;margin-bottom:14px}
        .ai-list{display:flex;flex-direction:column;gap:6px}
        .ai-list-item{display:flex;align-items:flex-start;gap:8px;font-size:12px;color:#374151;line-height:1.45}
        .ai-list-dot{width:6px;height:6px;border-radius:50%;flex-shrink:0;margin-top:4px}
        .ai-actions{display:flex;gap:10px;margin-top:16px;flex-wrap:wrap}
        .ai-btn{display:flex;align-items:center;gap:6px;padding:8px 14px;border-radius:9px;font-size:12px;font-weight:600;cursor:pointer;transition:all .18s;white-space:nowrap;font-family:'Plus Jakarta Sans',sans-serif}
        .ai-btn.shortlist{background:rgba(34,197,94,.1);color:#16a34a;border:1.5px solid rgba(34,197,94,.25)}
        .ai-btn.shortlist:hover{background:rgba(34,197,94,.18)}
        .ai-btn.reject{background:rgba(239,68,68,.08);color:#ef4444;border:1.5px solid rgba(239,68,68,.2)}
        .ai-btn.reject:hover{background:rgba(239,68,68,.14)}
        .ai-btn.view{background:#f8fafc;color:#374151;border:1.5px solid #e2e8f0}
        .ai-btn.view:hover{border-color:#7C3AED;color:#7C3AED}

        .pending-badge{display:inline-flex;align-items:center;gap:5px;font-size:11px;font-weight:600;color:#94a3b8;background:#f8fafc;border:1px solid #e2e8f0;padding:4px 10px;border-radius:20px}

        .empty-state{background:#fff;border:1px dashed #e2e8f0;border-radius:16px;padding:52px 24px;text-align:center}
        .empty-icon{width:56px;height:56px;border-radius:14px;background:rgba(124,58,237,.08);display:flex;align-items:center;justify-content:center;margin:0 auto 14px}
        .empty-title{font-size:15px;font-weight:700;color:#0f172a;margin-bottom:6px}
        .empty-sub{font-size:13px;color:#94a3b8}
.status-pill{display:inline-flex;align-items:center;gap:5px;font-size:11px;font-weight:700;padding:4px 11px;border-radius:20px}

.pdf-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:100;animation:fadeIn .2s ease}
       

  .delete-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:200;display:flex;align-items:center;justify-content:center;padding:20px}
        .delete-dialog{background:#fff;border-radius:16px;padding:28px;width:100%;max-width:420px;box-shadow:0 20px 60px rgba(0,0,0,.2)}
        .delete-dialog-title{font-size:17px;font-weight:800;color:#0f172a;margin-bottom:6px}
        .delete-dialog-sub{font-size:13px;color:#64748b;margin-bottom:20px;line-height:1.5}
        .delete-warning{background:rgba(239,68,68,.06);border:1px solid rgba(239,68,68,.2);border-radius:10px;padding:12px 14px;font-size:12px;color:#dc2626;font-weight:500;margin-bottom:16px;line-height:1.5}
        .delete-confirm-input{width:100%;padding:10px 14px;border:1.5px solid #e2e8f0;border-radius:10px;font-size:13px;font-family:'Plus Jakarta Sans',sans-serif;color:#0f172a;outline:none;margin-bottom:16px;transition:border-color .2s}
        .delete-confirm-input:focus{border-color:#ef4444;box-shadow:0 0 0 3px rgba(239,68,68,.08)}
        .delete-dialog-actions{display:flex;gap:10px;justify-content:flex-end}
        .btn-delete{display:inline-flex;align-items:center;gap:6px;padding:9px 18px;border-radius:9px;background:#ef4444;border:none;font-size:13px;font-weight:700;color:#fff;cursor:pointer;transition:all .18s;font-family:'Plus Jakarta Sans',sans-serif}
        .btn-delete:hover:not(:disabled){background:#dc2626}
        .btn-delete:disabled{opacity:.5;cursor:not-allowed}
        .btn-cancel-del{display:inline-flex;align-items:center;gap:6px;padding:9px 16px;border-radius:9px;border:1.5px solid #e2e8f0;background:#fff;font-size:13px;font-weight:600;color:#374151;cursor:pointer;font-family:'Plus Jakarta Sans',sans-serif}

        .upload-panel{background:#fff;
        .upload-panel{background:#fff;border:1px solid #e2e8f0;border-radius:14px;margin-bottom:20px;overflow:hidden}
        .upload-panel-header{display:flex;align-items:center;justify-content:space-between;padding:14px 18px;cursor:pointer;transition:background .18s}
        .upload-panel-header:hover{background:#f8fafc}
        .upload-panel-title{font-size:13px;font-weight:700;color:#0f172a;display:flex;align-items:center;gap:8px}
        .upload-panel-body{padding:16px 18px;border-top:1px solid #f1f5f9}
        .upload-drop{border:2px dashed #e2e8f0;border-radius:10px;padding:28px 20px;text-align:center;cursor:pointer;transition:all .2s}
        .upload-drop:hover,.upload-drop.drag{border-color:#7C3AED;background:rgba(124,58,237,.03)}
        .upload-drop-title{font-size:13px;font-weight:700;color:#0f172a;margin:8px 0 3px}
        .upload-drop-sub{font-size:11px;color:#94a3b8}
        .upload-file-list{margin-top:12px;display:flex;flex-direction:column;gap:7px}
        .upload-file-row{display:flex;align-items:center;gap:10px;padding:8px 12px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px}
        .upload-file-name{flex:1;font-size:12px;font-weight:500;color:#0f172a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
        .upload-file-size{font-size:11px;color:#94a3b8;flex-shrink:0}
        .upload-actions{display:flex;gap:10px;margin-top:14px;flex-wrap:wrap}
        .btn-upload-trigger{display:inline-flex;align-items:center;gap:6px;padding:9px 18px;border-radius:9px;background:linear-gradient(135deg,#7C3AED,#5b21b6);border:none;font-size:12px;font-weight:700;color:#fff;cursor:pointer;font-family:'Plus Jakarta Sans',sans-serif;transition:transform .18s;box-shadow:0 3px 10px rgba(124,58,237,.25)}
        .btn-upload-trigger:hover:not(:disabled){transform:translateY(-1px)}
        .btn-upload-trigger:disabled{opacity:.6;cursor:not-allowed}
        .btn-upload-cancel{display:inline-flex;align-items:center;gap:6px;padding:9px 16px;border-radius:9px;border:1.5px solid #e2e8f0;background:#fff;font-size:12px;font-weight:600;color:#64748b;cursor:pointer;font-family:'Plus Jakarta Sans',sans-serif;transition:all .18s}
        .btn-upload-cancel:hover{border-color:#94a3b8;color:#374151}

        .interview-section{margin-top:16px;background:rgba(59,130,246,.03);border:1px solid rgba(59,130,246,.12);border-radius:10px;padding:14px 16px}
        .interview-title{font-size:11px;font-weight:700;color:#2563eb;text-transform:uppercase;letter-spacing:.06em;margin-bottom:12px;display:flex;align-items:center;justify-content:space-between}
        .interview-list{display:flex;flex-direction:column;gap:10px}
        .interview-item{display:flex;align-items:flex-start;gap:10px;font-size:12.5px;color:#374151;line-height:1.55}
        .interview-num{width:22px;height:22px;border-radius:6px;background:#2563eb;color:#fff;font-size:11px;font-weight:800;display:flex;align-items:center;justify-content:center;flex-shrink:0;margin-top:1px}
        .download-btn{display:inline-flex;align-items:center;gap:5px;padding:5px 12px;border-radius:7px;background:rgba(37,99,235,.1);color:#2563eb;border:1.5px solid rgba(37,99,235,.2);font-size:11px;font-weight:700;cursor:pointer;transition:all .18s;font-family:'Plus Jakarta Sans',sans-serif}
        .download-btn:hover{background:rgba(37,99,235,.18);border-color:rgba(37,99,235,.35)}
        @media(max-width:900px){.stats-row{grid-template-columns:repeat(2,1fr)}.ai-panel-grid{grid-template-columns:1fr}}
        @media(max-width:640px){.sd-page{padding:20px 16px 48px}.score-wrap{display:none}}
        .interview-section {
  margin-top: 16px;
  background: rgba(59,130,246,.03);
  border: 1px solid rgba(59,130,246,.12);
  border-radius: 10px;
  padding: 14px 16px;
}
.interview-title {
  font-size: 11px;
  font-weight: 700;
  color: #2563eb;
  text-transform: uppercase;
  letter-spacing: .06em;
  margin-bottom: 12px;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.interview-list {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.interview-item {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  font-size: 12.5px;
  color: #374151;
  line-height: 1.55;
}
.interview-num {
  width: 22px;
  height: 22px;
  border-radius: 6px;
  background: #2563eb;
  color: #fff;
  font-size: 11px;
  font-weight: 800;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  margin-top: 1px;
}
.download-btn {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  padding: 5px 12px;
  border-radius: 7px;
  background: rgba(37,99,235,.1);
  color: #2563eb;
  border: 1.5px solid rgba(37,99,235,.2);
  font-size: 11px;
  font-weight: 700;
  cursor: pointer;
  transition: all .18s;
  font-family: 'Plus Jakarta Sans', sans-serif;
}
.download-btn:hover {
  background: rgba(37,99,235,.18);
  border-color: rgba(37,99,235,.35);
}
      `}</style>

      <div className="sd-page">
        <Link href="/dashboard/screening" className="back-link reveal r1">
          <ArrowLeft size={15} /> Back to Screening
        </Link>

        {/* ── Session header ── */}
        <div className="header-card reveal r1">
          <div className="header-icon">
            <FileText size={22} color="#7C3AED" />
          </div>
          <div className="header-info">
            <div className="header-title">{session.name}</div>
            {session.description && (
              <div className="header-desc">{session.description}</div>
            )}
            <span
              className="status-pill"
              style={
                session.status === "active"
                  ? { color: "#16a34a", background: "rgba(34,197,94,.1)" }
                  : { color: "#64748b", background: "rgba(100,116,139,.1)" }
              }
            >
              {session.status === "active" ? "Active" : "Archived"}
            </span>
          </div>
          <div className="header-actions">
            {session.status === "active" && (
              <button
                className="btn-outline"
                onClick={() => {
                  setUploadPanelOpen(true);
                  setTimeout(() => {
                    document
                      .getElementById("upload-panel")
                      ?.scrollIntoView({ behavior: "smooth", block: "start" });
                  }, 100);
                }}
                style={{ color: "#7C3AED", borderColor: "rgba(124,58,237,.3)" }}
              >
                <Upload size={13} />
                Upload More CVs
              </button>
            )}
            <button
              className="btn-outline"
              onClick={() => setDeleteDialogOpen(true)}
              style={{ color: "#ef4444", borderColor: "rgba(239,68,68,.3)" }}
            >
              <Trash2 size={13} /> Delete
            </button>
            <button
              className="btn-outline"
              onClick={handleArchive}
              disabled={archiving}
            >
              <Archive size={13} />
              {archiving
                ? "Updating..."
                : session.status === "active"
                  ? "Archive"
                  : "Unarchive"}
            </button>
          </div>
        </div>

        {/* ── Upload More CVs Panel ── */}
        {uploadPanelOpen && session.status === "active" && (
          <div className="upload-panel reveal r1" id="upload-panel">
            <div
              className="upload-panel-header"
              onClick={() => setUploadPanelOpen(false)}
            >
              <div className="upload-panel-title">
                <Upload size={14} color="#7C3AED" />
                Upload More CVs
              </div>
              <ChevronUp size={15} color="#94a3b8" />
            </div>
            <div className="upload-panel-body">
              <div
                className={`upload-drop${uploadDragging ? " drag" : ""}`}
                onDragOver={(e) => {
                  e.preventDefault();
                  setUploadDragging(true);
                }}
                onDragLeave={() => setUploadDragging(false)}
                onDrop={handleUploadDrop}
                onClick={() => uploadFileInputRef.current?.click()}
              >
                <Upload size={20} color="#7C3AED" />
                <div className="upload-drop-title">
                  Drop CVs here or click to browse
                </div>
                <div className="upload-drop-sub">
                  PDF or DOCX · Multiple files
                </div>
                <input
                  ref={uploadFileInputRef}
                  type="file"
                  accept=".pdf,.docx"
                  multiple
                  style={{ display: "none" }}
                  onChange={(e) => {
                    if (e.target.files) addUploadFiles(e.target.files);
                  }}
                />
              </div>

              {uploadFiles.length > 0 && (
                <div className="upload-file-list">
                  {uploadFiles.map((f) => (
                    <div key={f.id} className="upload-file-row">
                      <FileText
                        size={14}
                        color="#7C3AED"
                        style={{ flexShrink: 0 }}
                      />
                      <span className="upload-file-name">{f.name}</span>
                      <span className="upload-file-size">
                        {(f.size / 1024).toFixed(0)} KB
                      </span>
                      <span style={{ flexShrink: 0 }}>
                        {f.status === "uploading" && (
                          <Loader2
                            size={13}
                            color="#7C3AED"
                            className="spinning"
                          />
                        )}
                        {f.status === "done" && (
                          <CheckCircle2 size={13} color="#16a34a" />
                        )}
                        {f.status === "error" && (
                          <span title={f.error}>
                            <AlertTriangle size={13} color="#ef4444" />
                          </span>
                        )}
                        {f.status === "pending" && (
                          <div
                            style={{
                              width: 13,
                              height: 13,
                              borderRadius: "50%",
                              background: "#e2e8f0",
                            }}
                          />
                        )}
                      </span>
                    </div>
                  ))}
                </div>
              )}

              <div className="upload-actions">
                <button
                  className="btn-upload-trigger"
                  onClick={handleScreenNewCVs}
                  disabled={
                    uploadTriggering ||
                    uploadFiles.filter((f) => f.status === "done").length ===
                      0 ||
                    uploadFiles.some((f) => f.status === "uploading")
                  }
                >
                  {uploadTriggering ? (
                    <>
                      <Loader2 size={13} className="spinning" /> Screening...
                    </>
                  ) : (
                    <>
                      <Zap size={13} /> Screen{" "}
                      {uploadFiles.filter((f) => f.status === "done").length} CV
                      {uploadFiles.filter((f) => f.status === "done").length !==
                      1
                        ? "s"
                        : ""}
                    </>
                  )}
                </button>
                <button
                  className="btn-upload-cancel"
                  onClick={() => {
                    setUploadPanelOpen(false);
                    setUploadFiles([]);
                  }}
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ── Stats ── */}
        <div className="stats-row reveal r2">
          <div className="stat-mini">
            <div
              className="sm-icon"
              style={{ background: "rgba(124,58,237,.1)" }}
            >
              <Users size={17} color="#7C3AED" />
            </div>
            <div>
              <div className="sm-val">{candidates.length}</div>
              <div className="sm-lbl">Total CVs</div>
            </div>
          </div>
          <div className="stat-mini">
            <div
              className="sm-icon"
              style={{ background: "rgba(34,197,94,.1)" }}
            >
              <Zap size={17} color="#22c55e" />
            </div>
            <div>
              <div className="sm-val">{screened}</div>
              <div className="sm-lbl">AI Screened</div>
            </div>
          </div>
          <div className="stat-mini">
            <div
              className="sm-icon"
              style={{ background: "rgba(245,158,11,.1)" }}
            >
              <Star size={17} color="#f59e0b" />
            </div>
            <div>
              <div className="sm-val">{shortlisted}</div>
              <div className="sm-lbl">Shortlisted</div>
            </div>
          </div>
          <div className="stat-mini">
            <div
              className="sm-icon"
              style={{ background: "rgba(59,130,246,.1)" }}
            >
              <TrendingUp size={17} color="#3b82f6" />
            </div>
            <div>
              <div className="sm-val">{avgScore ?? "—"}</div>
              <div className="sm-lbl">Avg AI Score</div>
            </div>
          </div>
        </div>

        {/* ── Toolbar ── */}
        <div className="toolbar reveal r3">
          <div className="search-wrap">
            <Search size={14} color="#94a3b8" className="search-ico" />
            <input
              className="search-inp"
              placeholder="Search candidates..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
          <div className="sel-wrap">
            <select
              className="filter-sel"
              value={scoreFilter}
              onChange={(e) =>
                setScoreFilter(e.target.value as typeof scoreFilter)
              }
            >
              <option value="all">All Scores</option>
              <option value="strong">Strong (80+)</option>
              <option value="good">Good (60–79)</option>
              <option value="fair">Fair (40–59)</option>
              <option value="weak">Weak (&lt;40)</option>
            </select>
            <ChevronDown size={13} color="#94a3b8" className="sel-arr" />
          </div>
          <button
            className={`sort-btn${sortBy === "score" ? " active" : ""}`}
            onClick={() => setSortBy(sortBy === "score" ? "date" : "score")}
          >
            <TrendingUp size={13} />
            {sortBy === "score" ? "By Score" : "By Date"}
          </button>
          {candidates.some(
            (c) =>
              c.screening_status === "processing" ||
              c.screening_status === "pending",
          ) && (
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 6,
                fontSize: 12,
                fontWeight: 600,
                color: "#7C3AED",
                background: "rgba(124,58,237,0.06)",
                border: "1px solid rgba(124,58,237,0.15)",
                borderRadius: 8,
                padding: "6px 12px",
              }}
            >
              <RefreshCw size={12} className="spinning" />
              Auto-updating...
            </div>
          )}
        </div>

        {/* ── Candidate list ── */}
        <div className="reveal r4">
          {filtered.length === 0 && (
            <div className="empty-state">
              <div className="empty-icon">
                <Users size={24} color="#7C3AED" />
              </div>
              <div className="empty-title">
                {candidates.length === 0
                  ? "No CVs uploaded yet"
                  : "No candidates match your filters"}
              </div>
              <div className="empty-sub">
                {candidates.length === 0
                  ? "Go back and upload CVs to this session."
                  : "Try adjusting your search or score filter."}
              </div>
            </div>
          )}

          {filtered.map((candidate) => {
            const sc = scoreColor(candidate.ai_score);
            const stCfg = statusConfig[candidate.status];
            const [fg, bg] = avatarColor(candidate.candidate_name);
            const isExpanded = expandedId === candidate.id;

            return (
              <div key={candidate.id} className="candidate-card">
                <div className="candidate-row">
                  <div
                    className="c-avatar"
                    style={{ background: bg, color: fg }}
                  >
                    {initials(candidate.candidate_name)}
                  </div>

                  <div className="c-info">
                    <div className="c-name">{candidate.candidate_name}</div>
                    <div className="c-meta">
                      {candidate.candidate_email && (
                        <span className="c-meta-item">
                          {candidate.candidate_email}
                        </span>
                      )}
                      <span className="c-dot" />
                      <span className="c-meta-item">
                        {timeAgo(candidate.applied_at)}
                      </span>
                    </div>
                  </div>

                  <div className="score-wrap">
                    {candidate.screening_status === "completed" &&
                    candidate.ai_score != null ? (
                      <>
                        <div
                          className="score-ring"
                          style={{
                            borderColor: sc.color,
                            color: sc.color,
                            background: sc.bg,
                          }}
                        >
                          {candidate.ai_score}
                        </div>
                        <span
                          className="score-label"
                          style={{ color: sc.color }}
                        >
                          {sc.label}
                        </span>
                        {candidate.ai_recommendation && (
                          <span
                            style={{
                              fontSize: 9,
                              fontWeight: 700,
                              padding: "2px 7px",
                              borderRadius: 20,
                              marginTop: 2,
                              background:
                                candidate.ai_recommendation === "shortlist"
                                  ? "rgba(34,197,94,.1)"
                                  : candidate.ai_recommendation === "consider"
                                    ? "rgba(245,158,11,.1)"
                                    : "rgba(239,68,68,.1)",
                              color:
                                candidate.ai_recommendation === "shortlist"
                                  ? "#16a34a"
                                  : candidate.ai_recommendation === "consider"
                                    ? "#d97706"
                                    : "#ef4444",
                            }}
                          >
                            {candidate.ai_recommendation === "shortlist"
                              ? "Shortlist"
                              : candidate.ai_recommendation === "consider"
                                ? "Consider"
                                : "Reject"}
                          </span>
                        )}
                      </>
                    ) : candidate.screening_status === "processing" ? (
                      <span className="pending-badge">
                        <RefreshCw size={11} className="spinning" /> Screening
                      </span>
                    ) : (
                      <span className="pending-badge">
                        <Clock size={11} /> Pending
                      </span>
                    )}
                  </div>

                  <div className="c-right" onClick={(e) => e.stopPropagation()}>
                    <span
                      className="c-status"
                      style={{ color: stCfg.color, background: stCfg.bg }}
                    >
                      {stCfg.label}
                    </span>
                    <button
                      className="expand-btn"
                      onClick={() =>
                        setExpandedId(isExpanded ? null : candidate.id)
                      }
                      style={{ cursor: "pointer" }}
                    >
                      {isExpanded ? (
                        <ChevronUp size={14} color="#64748b" />
                      ) : (
                        <ChevronDown size={14} color="#64748b" />
                      )}
                    </button>
                  </div>
                </div>

                {/* Expanded AI panel */}
                {isExpanded && candidate.screening_status === "completed" && (
                  <div className="ai-panel">
                    {candidate.ai_summary && (
                      <>
                        <div className="ai-section-title">
                          <Zap size={12} /> AI Summary
                        </div>
                        <div className="ai-summary">{candidate.ai_summary}</div>
                      </>
                    )}
                    <div className="ai-panel-grid">
                      {candidate.ai_strengths &&
                        candidate.ai_strengths.length > 0 && (
                          <div>
                            <div
                              className="ai-section-title"
                              style={{ color: "#16a34a" }}
                            >
                              <CheckCircle2 size={12} /> Strengths
                            </div>
                            <div className="ai-list">
                              {candidate.ai_strengths.map((s, i) => (
                                <div key={i} className="ai-list-item">
                                  <div
                                    className="ai-list-dot"
                                    style={{ background: "#22c55e" }}
                                  />
                                  {s}
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                      {candidate.ai_red_flags &&
                        candidate.ai_red_flags.length > 0 && (
                          <div>
                            <div
                              className="ai-section-title"
                              style={{ color: "#ef4444" }}
                            >
                              <AlertTriangle size={12} /> Red Flags
                            </div>
                            <div className="ai-list">
                              {candidate.ai_red_flags.map((f, i) => (
                                <div key={i} className="ai-list-item">
                                  <div
                                    className="ai-list-dot"
                                    style={{ background: "#ef4444" }}
                                  />
                                  {f}
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                    </div>
                    {candidate.ai_justification && (
                      <div style={{ marginTop: 14 }}>
                        <div className="ai-section-title">
                          <Target size={12} /> Score Justification
                        </div>
                        <div className="ai-summary" style={{ marginBottom: 0 }}>
                          {candidate.ai_justification}
                        </div>
                      </div>
                    )}
                    {/* Interview Questions */}
                    {/* Interview Questions */}
                    {candidate.interview_questions &&
                      candidate.interview_questions.length > 0 && (
                        <div className="interview-section">
                          <div className="interview-title">
                            <span
                              style={{
                                display: "flex",
                                alignItems: "center",
                                gap: 6,
                              }}
                            >
                              <MessageSquare size={12} />
                              Interview Questions
                            </span>
                            <button
                              className="download-btn"
                              onClick={(e) => {
                                e.stopPropagation();
                                downloadInterviewQuestions(
                                  candidate,
                                  session?.name ?? "Screening Session",
                                );
                              }}
                              style={{
                                display: "inline-flex",
                                alignItems: "center",
                                gap: 6,
                                padding: "6px 14px",
                                borderRadius: 8,
                                background:
                                  "linear-gradient(135deg,#2563eb,#1d4ed8)",
                                color: "#fff",
                                border: "none",
                                fontSize: 11,
                                fontWeight: 700,
                                cursor: "pointer",
                                fontFamily: "'Plus Jakarta Sans',sans-serif",
                                boxShadow: "0 2px 8px rgba(37,99,235,.35)",
                                transition: "all .18s",
                                letterSpacing: ".02em",
                              }}
                              onMouseEnter={(e) => {
                                e.currentTarget.style.transform =
                                  "translateY(-1px)";
                                e.currentTarget.style.boxShadow =
                                  "0 4px 14px rgba(37,99,235,.45)";
                              }}
                              onMouseLeave={(e) => {
                                e.currentTarget.style.transform =
                                  "translateY(0)";
                                e.currentTarget.style.boxShadow =
                                  "0 2px 8px rgba(37,99,235,.35)";
                              }}
                            >
                              <Download size={11} /> Download PDF
                            </button>
                          </div>
                          <div className="interview-list">
                            {candidate.interview_questions.map((q, i) => (
                              <div
                                key={i}
                                style={{
                                  display: "flex",
                                  alignItems: "flex-start",
                                  gap: 10,
                                  padding: "10px 12px",
                                  borderRadius: 8,
                                  background:
                                    i % 2 === 0
                                      ? "rgba(37,99,235,.04)"
                                      : "rgba(124,58,237,.03)",
                                  border: "1px solid",
                                  borderColor:
                                    i % 2 === 0
                                      ? "rgba(37,99,235,.1)"
                                      : "rgba(124,58,237,.08)",
                                  transition: "all .18s",
                                }}
                              >
                                {/* Number badge */}
                                <div
                                  style={{
                                    minWidth: 22,
                                    height: 22,
                                    borderRadius: 6,
                                    background:
                                      i % 2 === 0
                                        ? "linear-gradient(135deg,#2563eb,#1d4ed8)"
                                        : "linear-gradient(135deg,#7C3AED,#5b21b6)",
                                    color: "#fff",
                                    fontSize: 10,
                                    fontWeight: 800,
                                    display: "flex",
                                    alignItems: "center",
                                    justifyContent: "center",
                                    flexShrink: 0,
                                    marginTop: 1,
                                    boxShadow:
                                      i % 2 === 0
                                        ? "0 2px 6px rgba(37,99,235,.3)"
                                        : "0 2px 6px rgba(124,58,237,.3)",
                                  }}
                                >
                                  {i + 1}
                                </div>

                                {/* Question text */}
                                <div style={{ flex: 1 }}>
                                  <div
                                    style={{
                                      fontSize: 12,
                                      fontWeight: 600,
                                      color:
                                        i % 2 === 0 ? "#1e40af" : "#5b21b6",
                                      marginBottom: 3,
                                      textTransform: "uppercase",
                                      letterSpacing: ".04em",
                                      fontSizeAdjust: 9,
                                    }}
                                  >
                                    Question {i + 1}
                                  </div>
                                  <div
                                    style={{
                                      fontSize: 12.5,
                                      color: "#1e293b",
                                      lineHeight: 1.6,
                                      fontWeight: 500,
                                    }}
                                  >
                                    {q}
                                  </div>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                    <div className="ai-actions">
                      {candidate.status !== "shortlisted" && (
                        <button
                          className="ai-btn shortlist"
                          onClick={() =>
                            handleStatusChange(candidate.id, "shortlisted")
                          }
                          disabled={updatingIds.has(candidate.id)}
                        >
                          <CheckCircle2 size={13} />
                          {updatingIds.has(candidate.id)
                            ? "Saving..."
                            : "Shortlist"}
                        </button>
                      )}
                      {candidate.status !== "rejected" && (
                        <button
                          className="ai-btn reject"
                          onClick={() =>
                            handleStatusChange(candidate.id, "rejected")
                          }
                          disabled={updatingIds.has(candidate.id)}
                        >
                          <XCircle size={13} /> Reject
                        </button>
                      )}
                      {candidate.cv_url && (
                        <a
                          href={candidate.cv_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="ai-btn view"
                        >
                          <ExternalLink size={13} /> View CV
                        </a>
                      )}
                    </div>
                  </div>
                )}

                {isExpanded && candidate.screening_status === "pending" && (
                  <div
                    className="ai-panel"
                    style={{ textAlign: "center", padding: "24px 20px" }}
                  >
                    <div
                      style={{
                        fontSize: 13,
                        color: "#64748b",
                        fontWeight: 500,
                      }}
                    >
                      ⏳ Queued for AI screening. Results will appear shortly.
                    </div>
                  </div>
                )}

                {isExpanded && candidate.screening_status === "processing" && (
                  <div
                    className="ai-panel"
                    style={{ textAlign: "center", padding: "24px 20px" }}
                  >
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        gap: 8,
                        fontSize: 13,
                        color: "#7C3AED",
                        fontWeight: 600,
                      }}
                    >
                      <RefreshCw size={14} className="spinning" /> AI is
                      screening this CV...
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
        {/* ── Delete Confirmation Dialog ── */}
        {deleteDialogOpen && (
          <div
            className="delete-backdrop"
            onClick={() => {
              setDeleteDialogOpen(false);
              setDeleteConfirmText("");
            }}
          >
            <div className="delete-dialog" onClick={(e) => e.stopPropagation()}>
              <div className="delete-dialog-title">Delete Session</div>
              <div className="delete-dialog-sub">
                This will permanently delete <strong>{session?.name}</strong>,
                all uploaded CVs, and all AI screening results. This cannot be
                undone.
              </div>
              <div className="delete-warning">
                ⚠️ All CV files will be removed from storage. Screening results
                and interview questions will be lost permanently.
              </div>
              <input
                className="delete-confirm-input"
                placeholder='Type "DELETE" to confirm'
                value={deleteConfirmText}
                onChange={(e) => setDeleteConfirmText(e.target.value)}
                autoFocus
              />
              <div className="delete-dialog-actions">
                <button
                  className="btn-cancel-del"
                  onClick={() => {
                    setDeleteDialogOpen(false);
                    setDeleteConfirmText("");
                  }}
                >
                  Cancel
                </button>
                <button
                  className="btn-delete"
                  onClick={handleDeleteSession}
                  disabled={deleteConfirmText !== "DELETE" || deleting}
                >
                  <Trash2 size={13} />
                  {deleting ? "Deleting..." : "Delete Session"}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ── PDF Viewer Drawer ── */}
      </div>
    </>
  );
}
