"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import "../../../../Style/Dashboard/Screening/screening-details.css";
import {
  ArrowLeft,
  Users,
  Zap,
  Star,
  TrendingUp,
  Search,
  ChevronDown,
  ChevronUp,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  ExternalLink,
  RefreshCw,
  Clock,
  Target,
  Archive,
  FileText,
  MessageSquare,
  Download,
  Upload,
  Loader2,
  X,
  Trash2,
} from "lucide-react";
import jsPDF from "jspdf";

// ─── Types ────────────────────────────────────────────────────────────────────

type ScreeningStatus = "pending" | "processing" | "completed" | "failed";
type CandidateStatus = "new" | "reviewing" | "shortlisted" | "rejected";

interface BlindSession {
  id: string;
  name: string;
  description: string | null;
  status: "active" | "archived";
  cv_count: number;
  created_at: string;
}

interface Candidate {
  id: string;
  candidate_name: string;
  candidate_email: string;
  cv_url: string;
  status: CandidateStatus;
  screening_status: ScreeningStatus;
  ai_score: number | null;
  ai_summary: string | null;
  ai_strengths: string[] | null;
  ai_red_flags: string[] | null;
  ai_generated_score: number | null;
  authenticity_flags: string[] | null;
  ai_justification: string | null;
  interview_questions: string[] | null;
  applied_at: string;
  ai_recommendation: "shortlist" | "consider" | "reject" | null;
}

// ─── Config ───────────────────────────────────────────────────────────────────

const scoreColor = (score: number | null) => {
  if (!score)
    return { color: "#94a3b8", bg: "rgba(148,163,184,0.1)", label: "—" };
  if (score >= 80)
    return { color: "#16a34a", bg: "rgba(34,197,94,0.1)", label: "Strong" };
  if (score >= 60)
    return { color: "#d97706", bg: "rgba(245,158,11,0.1)", label: "Good" };
  if (score >= 40)
    return { color: "#ea580c", bg: "rgba(234,88,12,0.1)", label: "Fair" };
  return { color: "#ef4444", bg: "rgba(239,68,68,0.1)", label: "Weak" };
};

const statusConfig: Record<
  CandidateStatus,
  { label: string; color: string; bg: string }
> = {
  new: { label: "New", color: "#3b82f6", bg: "rgba(59,130,246,0.1)" },
  reviewing: {
    label: "Reviewing",
    color: "#d97706",
    bg: "rgba(245,158,11,0.1)",
  },
  shortlisted: {
    label: "Shortlisted",
    color: "#16a34a",
    bg: "rgba(34,197,94,0.1)",
  },
  rejected: { label: "Rejected", color: "#ef4444", bg: "rgba(239,68,68,0.1)" },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function timeAgo(dateStr: string) {
  const diff = Date.now() - new Date(dateStr).getTime();
  const days = Math.floor(diff / 86400000);
  const hours = Math.floor(diff / 3600000);
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  if (hours < 24) return `${hours}h ago`;
  if (days < 30) return `${days}d ago`;
  return new Date(dateStr).toLocaleDateString("en-PK", {
    day: "numeric",
    month: "short",
  });
}

function initials(name: string) {
  return name
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}

const AVATAR_COLORS = [
  ["#7C3AED", "#ede9fe"],
  ["#2563eb", "#dbeafe"],
  ["#16a34a", "#dcfce7"],
  ["#d97706", "#fef3c7"],
  ["#db2777", "#fce7f3"],
  ["#0891b2", "#cffafe"],
];
function avatarColor(name: string) {
  return AVATAR_COLORS[name.charCodeAt(0) % AVATAR_COLORS.length];
}

// ─── Download interview questions as .txt ─────────────────────────────────────
// Generates a plain text file HR can print or use in interviews.

function downloadInterviewQuestions(candidate: Candidate, sessionName: string) {
  const questions = candidate.interview_questions ?? [];
  const date = new Date().toLocaleDateString("en-PK", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  // ── Header background bar ──
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, pageW, 28, "F");

  // ── Header text ──
  doc.setFontSize(15).setFont("helvetica", "bold").setTextColor(255, 255, 255);
  doc.text("Interview Questions", 14, 17);
  doc.setFontSize(9).setFont("helvetica", "normal").setTextColor(220, 210, 255);
  doc.text("Generated by SahiScreen AI", pageW - 14, 17, { align: "right" });

  // ── Meta info box ──
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 34, pageW - 28, 26, 3, 3, "FD");

  doc.setFontSize(9).setFont("helvetica", "bold").setTextColor(100, 116, 139);
  doc.text("CANDIDATE", 20, 43);
  doc.text("SESSION", 85, 43);
  doc.text("DATE", 155, 43);

  doc.setFontSize(10).setFont("helvetica", "bold").setTextColor(15, 23, 42);
  doc.text(candidate.candidate_name, 20, 52);
  doc.text(sessionName, 85, 52, { maxWidth: 60 });
  doc.text(date, 155, 52, { maxWidth: 40 });

  // ── Divider ──
  doc.setDrawColor(124, 58, 237);
  doc.setLineWidth(0.5);
  doc.line(14, 66, pageW - 14, 66);

  // ── Questions ──
  let y = 76;

  questions.forEach((q, i) => {
    const lines = doc.splitTextToSize(q, pageW - 50);
    const blockH = lines.length * 6 + 10;

    if (y + blockH > pageH - 24) {
      doc.addPage();

      // Repeat header on new page
      doc.setFillColor(124, 58, 237);
      doc.rect(0, 0, pageW, 18, "F");
      doc
        .setFontSize(9)
        .setFont("helvetica", "bold")
        .setTextColor(255, 255, 255);
      doc.text("Interview Questions — " + candidate.candidate_name, 14, 12);

      y = 28;
    }

    // Number badge background
    doc.setFillColor(124, 58, 237);
    doc.roundedRect(14, y - 4, 8, 8, 1.5, 1.5, "F");

    // Number
    doc.setFontSize(8).setFont("helvetica", "bold").setTextColor(255, 255, 255);
    doc.text(String(i + 1), 18, y + 1.5, { align: "center" });

    // Question text
    doc
      .setFontSize(10.5)
      .setFont("helvetica", "normal")
      .setTextColor(55, 65, 81);
    doc.text(lines, 28, y + 1);

    y += blockH;

    // Light separator between questions
    if (i < questions.length - 1) {
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.3);
      doc.line(28, y - 2, pageW - 14, y - 2);
    }
  });

  // ── Footer ──
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);

    doc.setFillColor(248, 250, 252);
    doc.rect(0, pageH - 14, pageW, 14, "F");
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(0, pageH - 14, pageW, pageH - 14);

    doc.setFontSize(8).setFont("helvetica", "bold").setTextColor(124, 58, 237);
    doc.text("SahiScreen", 14, pageH - 5);

    doc.setFont("helvetica", "normal").setTextColor(100, 116, 139);
    doc.text("Trustable", 35, pageH - 5);

    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${p} of ${totalPages}`, pageW - 14, pageH - 5, {
      align: "right",
    });
  }

  doc.save(
    `Interview_Questions_${candidate.candidate_name.replace(/\s+/g, "_")}.pdf`,
  );
}

// ─── Animated screening ring ──────────────────────────────────────────────────

function ProcessingRing() {
  const [progress, setProgress] = useState(12);
  const size = 48;
  const stroke = 3.5;
  const radius = (size - stroke) / 2;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (progress / 100) * circumference;

  useEffect(() => {
    const interval = setInterval(() => {
      setProgress((p) => {
        if (p >= 89) return 89;
        const step = p < 40 ? 1.8 : p < 65 ? 1.1 : 0.5;
        return Math.min(p + step, 89);
      });
    }, 400);
    return () => clearInterval(interval);
  }, []);

  const color = progress >= 60 ? "#d97706" : "#7C3AED";

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 3,
      }}
    >
      <div style={{ position: "relative", width: size, height: size }}>
        <svg width={size} height={size} style={{ transform: "rotate(-90deg)" }}>
          <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            fill="none"
            stroke="#e2e8f0"
            strokeWidth={stroke}
          />
          <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            fill="none"
            stroke={color}
            strokeWidth={stroke}
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            strokeLinecap="round"
            style={{
              transition: "stroke-dashoffset 0.4s ease, stroke 0.6s ease",
            }}
          />
        </svg>
        <div
          style={{
            position: "absolute",
            inset: 0,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <span
            style={{
              fontSize: 11,
              fontWeight: 800,
              color,
              lineHeight: 1,
              transition: "color 0.6s ease",
            }}
          >
            {Math.round(progress)}%
          </span>
        </div>
      </div>
      <span
        style={{
          fontSize: 9,
          fontWeight: 700,
          color: "#7C3AED",
          letterSpacing: ".03em",
          textTransform: "uppercase",
        }}
      >
        Screening
      </span>
    </div>
  );
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function BlindScreeningDetailPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();

  const [session, setSession] = useState<BlindSession | null>(null);
  const [candidates, setCandidates] = useState<Candidate[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [scoreFilter, setScoreFilter] = useState<
    "all" | "strong" | "good" | "fair" | "weak"
  >("all");
  const [sortBy, setSortBy] = useState<"score" | "date">("score");
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [updatingIds, setUpdatingIds] = useState<Set<string>>(new Set());
  const [archiving, setArchiving] = useState(false);
  const [uploadPanelOpen, setUploadPanelOpen] = useState(false);
  const [uploadFiles, setUploadFiles] = useState<
    Array<{
      id: string;
      name: string;
      size: number;
      status: "pending" | "uploading" | "done" | "error";
      error?: string;
    }>
  >([]);
  const [uploadDragging, setUploadDragging] = useState(false);
  const [uploadTriggering, setUploadTriggering] = useState(false);
  const uploadFileInputRef = useRef<HTMLInputElement>(null);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [deleteConfirmText, setDeleteConfirmText] = useState("");
  const [deleting, setDeleting] = useState(false);

  const lock = (id: string) => setUpdatingIds((p) => new Set(p).add(id));
  const unlock = (id: string) =>
    setUpdatingIds((p) => {
      const n = new Set(p);
      n.delete(id);
      return n;
    });

  // ─── Animated screening ring ──────────────────────────────────────────────────

  function ProcessingRing() {
    const [progress, setProgress] = useState(12);
    const size = 48;
    const stroke = 3.5;
    const radius = (size - stroke) / 2;
    const circumference = 2 * Math.PI * radius;
    const offset = circumference - (progress / 100) * circumference;

    useEffect(() => {
      // Crawl from 12 → 89 slowly, never completes (real completion triggers re-render)
      const interval = setInterval(() => {
        setProgress((p) => {
          if (p >= 89) return 89; // stall near end — never fake 100%
          // Slow down as it approaches 89
          const step = p < 40 ? 1.8 : p < 65 ? 1.1 : 0.5;
          return Math.min(p + step, 89);
        });
      }, 400);
      return () => clearInterval(interval);
    }, []);

    // Color transitions: purple → amber at 60+
    const color = progress >= 60 ? "#d97706" : "#7C3AED";
    const trackColor =
      progress >= 60 ? "rgba(245,158,11,0.12)" : "rgba(124,58,237,0.1)";

    return (
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          gap: 3,
        }}
      >
        <div style={{ position: "relative", width: size, height: size }}>
          <svg
            width={size}
            height={size}
            style={{ transform: "rotate(-90deg)" }}
          >
            {/* Track */}
            <circle
              cx={size / 2}
              cy={size / 2}
              r={radius}
              fill="none"
              stroke="#e2e8f0"
              strokeWidth={stroke}
            />
            {/* Progress arc */}
            <circle
              cx={size / 2}
              cy={size / 2}
              r={radius}
              fill="none"
              stroke={color}
              strokeWidth={stroke}
              strokeDasharray={circumference}
              strokeDashoffset={offset}
              strokeLinecap="round"
              style={{
                transition: "stroke-dashoffset 0.4s ease, stroke 0.6s ease",
              }}
            />
          </svg>
          {/* Center number */}
          <div
            style={{
              position: "absolute",
              inset: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              flexDirection: "column",
            }}
          >
            <span
              style={{
                fontSize: 11,
                fontWeight: 800,
                color,
                lineHeight: 1,
                transition: "color 0.6s ease",
              }}
            >
              {Math.round(progress)}%
            </span>
          </div>
        </div>
        <span
          style={{
            fontSize: 9,
            fontWeight: 700,
            color: "#7C3AED",
            letterSpacing: ".03em",
            textTransform: "uppercase",
          }}
        >
          Screening
        </span>
      </div>
    );
  }
  // ── Upload more CVs helpers ───────────────────────────────────────────────

  const toBase64Upload = (file: File): Promise<string> =>
    new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve((reader.result as string).split(",")[1]);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });

  const uploadOneFile = async (file: File, fileId: string) => {
    setUploadFiles((prev) =>
      prev.map((f) => (f.id === fileId ? { ...f, status: "uploading" } : f)),
    );

    try {
      const base64 = await toBase64Upload(file);
      const res = await fetch(`/api/blind-screening/${id}/upload`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          file_base64: base64,
          original_filename: file.name,
          file_type: file.type,
          file_size_kb: Math.round(file.size / 1024),
        }),
      });

      const data = await res.json();
      if (!res.ok) {
        setUploadFiles((prev) =>
          prev.map((f) =>
            f.id === fileId
              ? { ...f, status: "error", error: data.error ?? "Upload failed" }
              : f,
          ),
        );
      } else {
        setUploadFiles((prev) =>
          prev.map((f) => (f.id === fileId ? { ...f, status: "done" } : f)),
        );
      }
    } catch {
      setUploadFiles((prev) =>
        prev.map((f) =>
          f.id === fileId
            ? { ...f, status: "error", error: "Network error" }
            : f,
        ),
      );
    }
  };

  const addUploadFiles = async (newFiles: FileList | File[]) => {
    const arr = Array.from(newFiles).filter(
      (f) =>
        f.type === "application/pdf" ||
        f.name.endsWith(".pdf") ||
        f.name.endsWith(".docx"),
    );
    const entries = arr.map((f) => ({
      id: crypto.randomUUID(),
      name: f.name,
      size: f.size,
      status: "pending" as const,
    }));
    setUploadFiles((prev) => [...prev, ...entries]);
    for (let i = 0; i < arr.length; i++) {
      await uploadOneFile(arr[i], entries[i].id);
    }
  };

  const handleUploadDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setUploadDragging(false);
    addUploadFiles(e.dataTransfer.files);
  };

  const handleScreenNewCVs = async () => {
    setUploadTriggering(true);
    try {
      await fetch(`/api/blind-screening/${id}/trigger`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      setUploadFiles([]);
      setUploadPanelOpen(false);
      fetchData(true);
    } catch {
      // silent — polling will catch results
    } finally {
      setUploadTriggering(false);
    }
  };
  const handleDeleteSession = async () => {
    if (deleteConfirmText !== "DELETE") return;
    setDeleting(true);
    try {
      const res = await fetch(`/api/blind-screening/${id}`, {
        method: "DELETE",
      });
      if (res.ok) {
        router.push("/dashboard/screening");
      }
    } catch {
      // silent
    } finally {
      setDeleting(false);
    }
  };
  const fetchData = useCallback(
    async (silent = false) => {
      if (!silent) setLoading(true);
      try {
        const res = await fetch(`/api/blind-screening/${id}`);
        if (!res.ok) return;
        const json = await res.json();
        if (json.session) setSession(json.session);
        if (json.candidates) {
          setCandidates(json.candidates);
        }
      } catch {
        /* silent */
      } finally {
        if (!silent) setLoading(false);
      }
    },
    [id],
  );

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // Polling while CVs are processing
  useEffect(() => {
    const hasProcessing = candidates.some(
      (c) =>
        c.screening_status === "processing" || c.screening_status === "pending",
    );
    if (!hasProcessing) return;
    const interval = setInterval(() => fetchData(true), 8000);
    return () => clearInterval(interval);
  }, [candidates, fetchData]);

  const handleStatusChange = async (
    candidateId: string,
    status: CandidateStatus,
  ) => {
    if (updatingIds.has(candidateId)) return;
    const prev = candidates;
    lock(candidateId);
    setCandidates((p) =>
      p.map((c) => (c.id === candidateId ? { ...c, status } : c)),
    );

    try {
      const res = await fetch(`/api/candidates/${candidateId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status, hr_notes: "" }),
      });
      if (!res.ok) setCandidates(prev);
      const err = await res.json();
      console.error("Status update failed:", err);
    } catch {
      setCandidates(prev);
    } finally {
      unlock(candidateId);
    }
  };

  const handleArchive = async () => {
    if (!session || archiving) return;
    setArchiving(true);
    const res = await fetch(`/api/blind-screening/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        status: session.status === "active" ? "archived" : "active",
      }),
    });
    if (res.ok) {
      const data = await res.json();
      setSession(data.session);
    }
    setArchiving(false);
  };

  const filtered = candidates
    .filter((c) => {
      if (
        search &&
        !c.candidate_name.toLowerCase().includes(search.toLowerCase())
      )
        return false;
      if (scoreFilter !== "all") {
        const s = c.ai_score ?? 0;
        if (scoreFilter === "strong" && s < 80) return false;
        if (scoreFilter === "good" && (s < 60 || s >= 80)) return false;
        if (scoreFilter === "fair" && (s < 40 || s >= 60)) return false;
        if (scoreFilter === "weak" && s >= 40) return false;
      }
      return true;
    })
    .sort((a, b) =>
      sortBy === "score"
        ? (b.ai_score ?? -1) - (a.ai_score ?? -1)
        : new Date(b.applied_at).getTime() - new Date(a.applied_at).getTime(),
    );

  const screened = candidates.filter(
    (c) => c.screening_status === "completed",
  ).length;
  const shortlisted = candidates.filter(
    (c) => c.status === "shortlisted",
  ).length;
  const scoredCandidates = candidates.filter((c) => c.ai_score !== null);
  const avgScore =
    scoredCandidates.length > 0
      ? Math.round(
          scoredCandidates.reduce((s, c) => s + (c.ai_score ?? 0), 0) /
            scoredCandidates.length,
        )
      : null;

  if (loading)
    return (
      <div
        style={{ padding: 32, fontFamily: "'Plus Jakarta Sans',sans-serif" }}
      >
        {[1, 2, 3].map((i) => (
          <div
            key={i}
            style={{
              background: "#fff",
              border: "1px solid #e2e8f0",
              borderRadius: 14,
              padding: "18px 20px",
              display: "flex",
              gap: 16,
              alignItems: "center",
              marginBottom: 10,
            }}
          >
            <div
              style={{
                width: 44,
                height: 44,
                borderRadius: 12,
                flexShrink: 0,
                background:
                  "linear-gradient(90deg,#f1f5f9 25%,#e2e8f0 50%,#f1f5f9 75%)",
                backgroundSize: "800px 100%",
                animation: "shimmer 1.4s infinite",
              }}
            />
            <div
              style={{
                flex: 1,
                display: "flex",
                flexDirection: "column",
                gap: 8,
              }}
            >
              <div
                style={{
                  height: 14,
                  width: "35%",
                  borderRadius: 6,
                  background:
                    "linear-gradient(90deg,#f1f5f9 25%,#e2e8f0 50%,#f1f5f9 75%)",
                  backgroundSize: "800px 100%",
                  animation: "shimmer 1.4s infinite",
                }}
              />
              <div
                style={{
                  height: 11,
                  width: "55%",
                  borderRadius: 6,
                  background:
                    "linear-gradient(90deg,#f1f5f9 25%,#e2e8f0 50%,#f1f5f9 75%)",
                  backgroundSize: "800px 100%",
                  animation: "shimmer 1.4s infinite",
                }}
              />
            </div>
          </div>
        ))}
      </div>
    );

  if (!session)
    return (
      <div
        style={{
          padding: 32,
          textAlign: "center",
          fontFamily: "'Plus Jakarta Sans',sans-serif",
        }}
      >
        <div style={{ fontSize: 16, fontWeight: 700, color: "#0f172a" }}>
          Session not found
        </div>
        <Link
          href="/dashboard/screening"
          style={{
            color: "#7C3AED",
            fontSize: 13,
            marginTop: 8,
            display: "inline-block",
          }}
        >
          ← Back to Screening
        </Link>
      </div>
    );

  return (
    <>
      <div className="sd-page">
        <Link href="/dashboard/screening" className="back-link reveal r1">
          <ArrowLeft size={15} /> Back to Screening
        </Link>

        {/* ── Session header ── */}
        <div className="header-card reveal r1">
          <div className="header-icon">
            <FileText size={22} color="#7C3AED" />
          </div>
          <div className="header-info">
            <div className="header-title">{session.name}</div>
            {session.description && (
              <div className="header-desc">{session.description}</div>
            )}
            <span
              className="status-pill"
              style={
                session.status === "active"
                  ? { color: "#16a34a", background: "rgba(34,197,94,.1)" }
                  : { color: "#64748b", background: "rgba(100,116,139,.1)" }
              }
            >
              {session.status === "active" ? "Active" : "Archived"}
            </span>
          </div>
          <div className="header-actions">
            {session.status === "active" && (
              <button
                className="btn-outline"
                onClick={() => {
                  setUploadPanelOpen(true);
                  setTimeout(() => {
                    document
                      .getElementById("upload-panel")
                      ?.scrollIntoView({ behavior: "smooth", block: "start" });
                  }, 100);
                }}
                style={{ color: "#7C3AED", borderColor: "rgba(124,58,237,.3)" }}
              >
                <Upload size={13} />
                Upload More CVs
              </button>
            )}
            <button
              className="btn-outline"
              onClick={() => setDeleteDialogOpen(true)}
              style={{ color: "#ef4444", borderColor: "rgba(239,68,68,.3)" }}
            >
              <Trash2 size={13} /> Delete
            </button>
            <button
              className="btn-outline"
              onClick={handleArchive}
              disabled={archiving}
            >
              <Archive size={13} />
              {archiving
                ? "Updating..."
                : session.status === "active"
                  ? "Archive"
                  : "Unarchive"}
            </button>
          </div>
        </div>

        {/* ── Upload More CVs Panel ── */}
        {uploadPanelOpen && session.status === "active" && (
          <div className="upload-panel reveal r1" id="upload-panel">
            <div
              className="upload-panel-header"
              onClick={() => setUploadPanelOpen(false)}
            >
              <div className="upload-panel-title">
                <Upload size={14} color="#7C3AED" />
                Upload More CVs
              </div>
              <ChevronUp size={15} color="#94a3b8" />
            </div>
            <div className="upload-panel-body">
              <div
                className={`upload-drop${uploadDragging ? " drag" : ""}`}
                onDragOver={(e) => {
                  e.preventDefault();
                  setUploadDragging(true);
                }}
                onDragLeave={() => setUploadDragging(false)}
                onDrop={handleUploadDrop}
                onClick={() => uploadFileInputRef.current?.click()}
              >
                <center>
                  <Upload size={20} color="#7C3AED" />
                </center>
                <div className="upload-drop-title">
                  Drop CVs here or click to browse
                </div>
                <div className="upload-drop-sub">
                  PDF or DOCX · Multiple files
                </div>
                <input
                  ref={uploadFileInputRef}
                  type="file"
                  accept=".pdf,.docx"
                  multiple
                  style={{ display: "none" }}
                  onChange={(e) => {
                    if (e.target.files) addUploadFiles(e.target.files);
                  }}
                />
              </div>

              {uploadFiles.length > 0 && (
                <div className="upload-file-list">
                  {uploadFiles.map((f) => (
                    <div key={f.id} className="upload-file-row">
                      <FileText
                        size={14}
                        color="#7C3AED"
                        style={{ flexShrink: 0 }}
                      />
                      <span className="upload-file-name">{f.name}</span>
                      <span className="upload-file-size">
                        {(f.size / 1024).toFixed(0)} KB
                      </span>
                      <span style={{ flexShrink: 0 }}>
                        {f.status === "uploading" && (
                          <Loader2
                            size={13}
                            color="#7C3AED"
                            className="spinning"
                          />
                        )}
                        {f.status === "done" && (
                          <CheckCircle2 size={13} color="#16a34a" />
                        )}
                        {f.status === "error" && (
                          <span title={f.error}>
                            <AlertTriangle size={13} color="#ef4444" />
                          </span>
                        )}
                        {f.status === "pending" && (
                          <div
                            style={{
                              width: 13,
                              height: 13,
                              borderRadius: "50%",
                              background: "#e2e8f0",
                            }}
                          />
                        )}
                      </span>
                    </div>
                  ))}
                </div>
              )}

              <div className="upload-actions">
                <button
                  className="btn-upload-trigger"
                  onClick={handleScreenNewCVs}
                  disabled={
                    uploadTriggering ||
                    uploadFiles.filter((f) => f.status === "done").length ===
                      0 ||
                    uploadFiles.some((f) => f.status === "uploading")
                  }
                >
                  {uploadTriggering ? (
                    <>
                      <Loader2 size={13} className="spinning" /> Screening...
                    </>
                  ) : (
                    <>
                      <Zap size={13} /> Screen{" "}
                      {uploadFiles.filter((f) => f.status === "done").length} CV
                      {uploadFiles.filter((f) => f.status === "done").length !==
                      1
                        ? "s"
                        : ""}
                    </>
                  )}
                </button>
                <button
                  className="btn-upload-cancel"
                  onClick={() => {
                    setUploadPanelOpen(false);
                    setUploadFiles([]);
                  }}
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ── Stats ── */}
        <div className="stats-row reveal r2">
          <div className="stat-mini">
            <div
              className="sm-icon"
              style={{ background: "rgba(124,58,237,.1)" }}
            >
              <Users size={17} color="#7C3AED" />
            </div>
            <div>
              <div className="sm-val">{candidates.length}</div>
              <div className="sm-lbl">Total CVs</div>
            </div>
          </div>
          <div className="stat-mini">
            <div
              className="sm-icon"
              style={{ background: "rgba(34,197,94,.1)" }}
            >
              <Zap size={17} color="#22c55e" />
            </div>
            <div>
              <div className="sm-val">{screened}</div>
              <div className="sm-lbl">AI Screened</div>
            </div>
          </div>
          <div className="stat-mini">
            <div
              className="sm-icon"
              style={{ background: "rgba(245,158,11,.1)" }}
            >
              <Star size={17} color="#f59e0b" />
            </div>
            <div>
              <div className="sm-val">{shortlisted}</div>
              <div className="sm-lbl">Shortlisted</div>
            </div>
          </div>
          <div className="stat-mini">
            <div
              className="sm-icon"
              style={{ background: "rgba(59,130,246,.1)" }}
            >
              <TrendingUp size={17} color="#3b82f6" />
            </div>
            <div>
              <div className="sm-val">{avgScore ?? "—"}</div>
              <div className="sm-lbl">Avg AI Score</div>
            </div>
          </div>
        </div>

        {/* ── Toolbar ── */}
        <div className="toolbar reveal r3">
          <div className="search-wrap">
            <Search size={14} color="#94a3b8" className="search-ico" />
            <input
              className="search-inp"
              placeholder="Search candidates..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
          <div className="sel-wrap">
            <select
              className="filter-sel"
              value={scoreFilter}
              onChange={(e) =>
                setScoreFilter(e.target.value as typeof scoreFilter)
              }
            >
              <option value="all">All Scores</option>
              <option value="strong">Strong (80+)</option>
              <option value="good">Good (60–79)</option>
              <option value="fair">Fair (40–59)</option>
              <option value="weak">Weak (&lt;40)</option>
            </select>
            <ChevronDown size={13} color="#94a3b8" className="sel-arr" />
          </div>
          <button
            className={`sort-btn${sortBy === "score" ? " active" : ""}`}
            onClick={() => setSortBy(sortBy === "score" ? "date" : "score")}
          >
            <TrendingUp size={13} />
            {sortBy === "score" ? "By Score" : "By Date"}
          </button>
          {candidates.some(
            (c) =>
              c.screening_status === "processing" ||
              c.screening_status === "pending",
          ) && (
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 6,
                fontSize: 12,
                fontWeight: 600,
                color: "#7C3AED",
                background: "rgba(124,58,237,0.06)",
                border: "1px solid rgba(124,58,237,0.15)",
                borderRadius: 8,
                padding: "6px 12px",
              }}
            >
              <RefreshCw size={12} className="spinning" />
              Auto-updating...
            </div>
          )}
        </div>

        {/* ── Candidate list ── */}
        <div className="reveal r4">
          {filtered.length === 0 && (
            <div className="empty-state">
              <div className="empty-icon">
                <Users size={24} color="#7C3AED" />
              </div>
              <div className="empty-title">
                {candidates.length === 0
                  ? "No CVs uploaded yet"
                  : "No candidates match your filters"}
              </div>
              <div className="empty-sub">
                {candidates.length === 0
                  ? "Go back and upload CVs to this session."
                  : "Try adjusting your search or score filter."}
              </div>
            </div>
          )}

          {filtered.map((candidate) => {
            const sc = scoreColor(candidate.ai_score);
            const stCfg = statusConfig[candidate.status];
            const [fg, bg] = avatarColor(candidate.candidate_name);
            const isExpanded = expandedId === candidate.id;

            return (
              <div key={candidate.id} className="candidate-card">
                <div className="candidate-row">
                  <div
                    className="c-avatar"
                    style={{ background: bg, color: fg }}
                  >
                    {initials(candidate.candidate_name)}
                  </div>

                  <div className="c-info">
                    <div className="c-name">{candidate.candidate_name}</div>
                    <div className="c-meta">
                      {candidate.candidate_email && (
                        <span className="c-meta-item">
                          {candidate.candidate_email}
                        </span>
                      )}
                      <span className="c-dot" />
                      <span className="c-meta-item">
                        {timeAgo(candidate.applied_at)}
                      </span>
                    </div>
                  </div>

                  <div className="score-wrap">
                    {candidate.screening_status === "completed" &&
                    candidate.ai_score != null ? (
                      <>
                        <div
                          className="score-ring"
                          style={{
                            borderColor: sc.color,
                            color: sc.color,
                            background: sc.bg,
                          }}
                        >
                          {candidate.ai_score}
                        </div>
                        <span
                          className="score-label"
                          style={{ color: sc.color }}
                        >
                          {sc.label}
                        </span>
                        {candidate.ai_recommendation && (
                          <span
                            style={{
                              fontSize: 9,
                              fontWeight: 700,
                              padding: "2px 7px",
                              borderRadius: 20,
                              marginTop: 2,
                              background:
                                candidate.ai_recommendation === "shortlist"
                                  ? "rgba(34,197,94,.1)"
                                  : candidate.ai_recommendation === "consider"
                                    ? "rgba(245,158,11,.1)"
                                    : "rgba(239,68,68,.1)",
                              color:
                                candidate.ai_recommendation === "shortlist"
                                  ? "#16a34a"
                                  : candidate.ai_recommendation === "consider"
                                    ? "#d97706"
                                    : "#ef4444",
                            }}
                          >
                            {candidate.ai_recommendation === "shortlist"
                              ? "Shortlist"
                              : candidate.ai_recommendation === "consider"
                                ? "Consider"
                                : "Reject"}
                          </span>
                        )}
                      </>
                    ) : candidate.screening_status === "processing" ? (
                      <ProcessingRing />
                    ) : (
                      <span className="pending-badge">
                        <Clock size={11} /> Pending
                      </span>
                    )}
                  </div>

                  <div className="c-right" onClick={(e) => e.stopPropagation()}>
                    <span
                      className="c-status"
                      style={{ color: stCfg.color, background: stCfg.bg }}
                    >
                      {stCfg.label}
                    </span>
                    <button
                      className="expand-btn"
                      onClick={() =>
                        setExpandedId(isExpanded ? null : candidate.id)
                      }
                      style={{ cursor: "pointer" }}
                    >
                      {isExpanded ? (
                        <ChevronUp size={14} color="#64748b" />
                      ) : (
                        <ChevronDown size={14} color="#64748b" />
                      )}
                    </button>
                  </div>
                </div>

                {/* Expanded AI panel */}
                {isExpanded && candidate.screening_status === "completed" && (
                  <div className="ai-panel">
                    {candidate.ai_summary && (
                      <>
                        <div className="ai-section-title">
                          <Zap size={12} /> AI Summary
                        </div>
                        <div className="ai-summary">{candidate.ai_summary}</div>
                      </>
                    )}
                    <div className="ai-panel-grid">
                      {candidate.ai_strengths &&
                        candidate.ai_strengths.length > 0 && (
                          <div>
                            <div
                              className="ai-section-title"
                              style={{ color: "#16a34a" }}
                            >
                              <CheckCircle2 size={12} /> Strengths
                            </div>
                            <div className="ai-list">
                              {candidate.ai_strengths.map((s, i) => (
                                <div key={i} className="ai-list-item">
                                  <div
                                    className="ai-list-dot"
                                    style={{ background: "#22c55e" }}
                                  />
                                  {s}
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                      {candidate.ai_red_flags &&
                        candidate.ai_red_flags.length > 0 && (
                          <div>
                            <div
                              className="ai-section-title"
                              style={{ color: "#ef4444" }}
                            >
                              <AlertTriangle size={12} /> Red Flags
                            </div>
                            <div className="ai-list">
                              {candidate.ai_red_flags.map((f, i) => (
                                <div key={i} className="ai-list-item">
                                  <div
                                    className="ai-list-dot"
                                    style={{ background: "#ef4444" }}
                                  />
                                  {f}
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                    </div>
                    {/* AI Detection Warning */}
                    {candidate.ai_generated_score !== null &&
                      candidate.ai_generated_score !== undefined && (
                        <div
                          style={{
                            marginTop: 14,
                            padding: "10px 14px",
                            borderRadius: 10,
                            background:
                              candidate.ai_generated_score > 60
                                ? "rgba(245,158,11,0.08)"
                                : "rgba(34,197,94,0.08)",
                            border: `1px solid ${
                              candidate.ai_generated_score > 60
                                ? "rgba(245,158,11,0.25)"
                                : "rgba(34,197,94,0.2)"
                            }`,
                            display: "flex",
                            alignItems: "flex-start",
                            gap: 10,
                          }}
                        >
                          <AlertTriangle
                            size={15}
                            color={
                              candidate.ai_generated_score > 60
                                ? "#d97706"
                                : "#16a34a"
                            }
                            style={{ marginTop: 1, flexShrink: 0 }}
                          />
                          <div>
                            <div
                              style={{
                                fontSize: 12,
                                fontWeight: 700,
                                color:
                                  candidate.ai_generated_score > 60
                                    ? "#d97706"
                                    : "#16a34a",
                                marginBottom: 4,
                              }}
                            >
                              AI-Written CV Score:{" "}
                              {candidate.ai_generated_score}/100
                              {candidate.ai_generated_score > 60
                                ? " — Likely AI-generated"
                                : " — Appears human-written"}
                            </div>
                            {candidate.authenticity_flags &&
                              candidate.authenticity_flags.length > 0 && (
                                <div
                                  style={{
                                    display: "flex",
                                    flexWrap: "wrap",
                                    gap: 5,
                                  }}
                                >
                                  {candidate.authenticity_flags.map(
                                    (flag, i) => (
                                      <span
                                        key={i}
                                        style={{
                                          fontSize: 11,
                                          fontWeight: 500,
                                          padding: "2px 8px",
                                          borderRadius: 20,
                                          background: "rgba(245,158,11,0.12)",
                                          color: "#92400e",
                                        }}
                                      >
                                        {flag}
                                      </span>
                                    ),
                                  )}
                                </div>
                              )}
                          </div>
                        </div>
                      )}
                    {candidate.ai_justification && (
                      <div style={{ marginTop: 14 }}>
                        <div className="ai-section-title">
                          <Target size={12} /> Score Justification
                        </div>
                        <div className="ai-summary" style={{ marginBottom: 0 }}>
                          {candidate.ai_justification}
                        </div>
                      </div>
                    )}
                    {/* Interview Questions */}
                    {/* Interview Questions */}
                    {candidate.interview_questions &&
                      candidate.interview_questions.length > 0 && (
                        <div className="interview-section">
                          <div className="interview-title">
                            <span
                              style={{
                                display: "flex",
                                alignItems: "center",
                                gap: 6,
                              }}
                            >
                              <MessageSquare size={12} />
                              Interview Questions
                            </span>
                            <button
                              className="download-btn"
                              onClick={(e) => {
                                e.stopPropagation();
                                downloadInterviewQuestions(
                                  candidate,
                                  session?.name ?? "Screening Session",
                                );
                              }}
                              style={{
                                display: "inline-flex",
                                alignItems: "center",
                                gap: 6,
                                padding: "6px 14px",
                                borderRadius: 8,
                                background:
                                  "linear-gradient(135deg,#2563eb,#1d4ed8)",
                                color: "#fff",
                                border: "none",
                                fontSize: 11,
                                fontWeight: 700,
                                cursor: "pointer",
                                fontFamily: "'Plus Jakarta Sans',sans-serif",
                                boxShadow: "0 2px 8px rgba(37,99,235,.35)",
                                transition: "all .18s",
                                letterSpacing: ".02em",
                              }}
                              onMouseEnter={(e) => {
                                e.currentTarget.style.transform =
                                  "translateY(-1px)";
                                e.currentTarget.style.boxShadow =
                                  "0 4px 14px rgba(37,99,235,.45)";
                              }}
                              onMouseLeave={(e) => {
                                e.currentTarget.style.transform =
                                  "translateY(0)";
                                e.currentTarget.style.boxShadow =
                                  "0 2px 8px rgba(37,99,235,.35)";
                              }}
                            >
                              <Download size={11} /> Download PDF
                            </button>
                          </div>
                          <div className="interview-list">
                            {candidate.interview_questions.map((q, i) => (
                              <div
                                key={i}
                                style={{
                                  display: "flex",
                                  alignItems: "flex-start",
                                  gap: 10,
                                  padding: "10px 12px",
                                  borderRadius: 8,
                                  background:
                                    i % 2 === 0
                                      ? "rgba(37,99,235,.04)"
                                      : "rgba(124,58,237,.03)",
                                  border: "1px solid",
                                  borderColor:
                                    i % 2 === 0
                                      ? "rgba(37,99,235,.1)"
                                      : "rgba(124,58,237,.08)",
                                  transition: "all .18s",
                                }}
                              >
                                {/* Number badge */}
                                <div
                                  style={{
                                    minWidth: 22,
                                    height: 22,
                                    borderRadius: 6,
                                    background:
                                      i % 2 === 0
                                        ? "linear-gradient(135deg,#2563eb,#1d4ed8)"
                                        : "linear-gradient(135deg,#7C3AED,#5b21b6)",
                                    color: "#fff",
                                    fontSize: 10,
                                    fontWeight: 800,
                                    display: "flex",
                                    alignItems: "center",
                                    justifyContent: "center",
                                    flexShrink: 0,
                                    marginTop: 1,
                                    boxShadow:
                                      i % 2 === 0
                                        ? "0 2px 6px rgba(37,99,235,.3)"
                                        : "0 2px 6px rgba(124,58,237,.3)",
                                  }}
                                >
                                  {i + 1}
                                </div>

                                {/* Question text */}
                                <div style={{ flex: 1 }}>
                                  <div
                                    style={{
                                      fontSize: 12,
                                      fontWeight: 600,
                                      color:
                                        i % 2 === 0 ? "#1e40af" : "#5b21b6",
                                      marginBottom: 3,
                                      textTransform: "uppercase",
                                      letterSpacing: ".04em",
                                      fontSizeAdjust: 9,
                                    }}
                                  >
                                    Question {i + 1}
                                  </div>
                                  <div
                                    style={{
                                      fontSize: 12.5,
                                      color: "#1e293b",
                                      lineHeight: 1.6,
                                      fontWeight: 500,
                                    }}
                                  >
                                    {q}
                                  </div>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                    <div className="ai-actions">
                      {candidate.status !== "shortlisted" && (
                        <button
                          className="ai-btn shortlist"
                          onClick={() =>
                            handleStatusChange(candidate.id, "shortlisted")
                          }
                          disabled={updatingIds.has(candidate.id)}
                        >
                          <CheckCircle2 size={13} />
                          {updatingIds.has(candidate.id)
                            ? "Saving..."
                            : "Shortlist"}
                        </button>
                      )}
                      {candidate.status !== "rejected" && (
                        <button
                          className="ai-btn reject"
                          onClick={() =>
                            handleStatusChange(candidate.id, "rejected")
                          }
                          disabled={updatingIds.has(candidate.id)}
                        >
                          <XCircle size={13} /> Reject
                        </button>
                      )}
                      {candidate.cv_url && (
                        <a
                          href={candidate.cv_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="ai-btn view"
                        >
                          <ExternalLink size={13} /> View CV
                        </a>
                      )}
                    </div>
                  </div>
                )}

                {isExpanded && candidate.screening_status === "pending" && (
                  <div
                    className="ai-panel"
                    style={{ textAlign: "center", padding: "24px 20px" }}
                  >
                    <div
                      style={{
                        fontSize: 13,
                        color: "#64748b",
                        fontWeight: 500,
                      }}
                    >
                      ⏳ Queued for AI screening. Results will appear shortly.
                    </div>
                  </div>
                )}

                {isExpanded && candidate.screening_status === "processing" && (
                  <div
                    className="ai-panel"
                    style={{ textAlign: "center", padding: "24px 20px" }}
                  >
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        gap: 8,
                        fontSize: 13,
                        color: "#7C3AED",
                        fontWeight: 600,
                      }}
                    >
                      <RefreshCw size={14} className="spinning" /> AI is
                      screening this CV...
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
        {/* ── Delete Confirmation Dialog ── */}
        {deleteDialogOpen && (
          <div
            className="delete-backdrop"
            onClick={() => {
              setDeleteDialogOpen(false);
              setDeleteConfirmText("");
            }}
          >
            <div className="delete-dialog" onClick={(e) => e.stopPropagation()}>
              <div className="delete-dialog-title">Delete Session</div>
              <div className="delete-dialog-sub">
                This will permanently delete <strong>{session?.name}</strong>,
                all uploaded CVs, and all AI screening results. This cannot be
                undone.
              </div>
              <div className="delete-warning">
                ⚠️ All CV files will be removed from storage. Screening results
                and interview questions will be lost permanently.
              </div>
              <input
                className="delete-confirm-input"
                placeholder='Type "DELETE" to confirm'
                value={deleteConfirmText}
                onChange={(e) => setDeleteConfirmText(e.target.value)}
                autoFocus
              />
              <div className="delete-dialog-actions">
                <button
                  className="btn-cancel-del"
                  onClick={() => {
                    setDeleteDialogOpen(false);
                    setDeleteConfirmText("");
                  }}
                >
                  Cancel
                </button>
                <button
                  className="btn-delete"
                  onClick={handleDeleteSession}
                  disabled={deleteConfirmText !== "DELETE" || deleting}
                >
                  <Trash2 size={13} />
                  {deleting ? "Deleting..." : "Delete Session"}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ── PDF Viewer Drawer ── */}
      </div>
    </>
  );
}
