"use client";

import {
  X,
  Check,
  ShieldCheck,
  GraduationCap,
  AlertTriangle,
} from "lucide-react";

const legacyPoints = [
  "Keyword matching only — 'Project Lead' scores high",
  "Cannot detect AI-generated or padded CVs",
  "Misses candidates from smaller cities or colleges",
  "No understanding of Pakistani institutions",
];

const sahiPoints = [
  "Evaluates logical flow, project complexity, and depth",
  "Detects if a CV was generated by AI models",
  "Weights university prestige and industry standards",
  "Red flag detection for job hopping and skill gaps",
];

const featureBullets = [
  {
    icon: ShieldCheck,
    text: "Detects if a CV was generated by AI models",
    color: "#7C3AED",
    bg: "#f3f0ff",
  },
  {
    icon: GraduationCap,
    text: "Weights university prestige and industry standards",
    color: "#0284c7",
    bg: "#e0f2fe",
  },
  {
    icon: AlertTriangle,
    text: "Red flag detection for job hopping and skill gaps",
    color: "#dc2626",
    bg: "#fee2e2",
  },
];

export default function ComparisonSection() {
  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap');

        .comparison-section {
          padding: 96px 24px;
          background: #f8fafc;
          position: relative;
          overflow: hidden;
        }

        .comparison-bg {
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: 
            radial-gradient(ellipse at 10% 50%, rgba(124,58,237,0.04) 0%, transparent 60%),
            radial-gradient(ellipse at 90% 50%, rgba(16,185,129,0.03) 0%, transparent 60%);
          pointer-events: none;
        }

        .comparison-inner {
          max-width: 1200px;
          margin: 0 auto;
          position: relative;
          z-index: 1;
        }

        .comparison-header {
          text-align: center;
          margin-bottom: 64px;
        }

        .comparison-title {
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 38px;
          font-weight: 800;
          color: #0f172a;
          letter-spacing: -1px;
          line-height: 1.2;
          margin: 0;
        }

        .comparison-title .line1 {
          display: block;
          color: #94a3b8;
          font-size: 22px;
          font-weight: 600;
          letter-spacing: 0px;
          margin-bottom: 4px;
          text-decoration: line-through;
          text-decoration-color: #cbd5e1;
        }

        .comparison-title .line2 {
          display: block;
          color: #0f172a;
        }

        .comparison-title .highlight {
          color: #7C3AED;
          position: relative;
        }

        /* Grid layout */
        .comparison-grid {
          display: grid;
          grid-template-columns: 1fr auto 1fr;
          gap: 0;
          align-items: stretch;
          background: white;
          border-radius: 20px;
          border: 1px solid #e2e8f0;
          overflow: hidden;
          box-shadow: 0 8px 40px rgba(0,0,0,0.06);
          margin-bottom: 48px;
        }

        /* Legacy ATS Panel */
        .panel-legacy {
          padding: 36px 32px;
          background: #fafafa;
          border-right: 1px solid #e2e8f0;
        }

        .panel-label {
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 11px;
          font-weight: 700;
          letter-spacing: 1px;
          text-transform: uppercase;
          margin-bottom: 20px;
          display: inline-flex;
          align-items: center;
          gap: 6px;
          padding: 4px 12px;
          border-radius: 100px;
        }

        .panel-label.legacy {
          background: #fee2e2;
          color: #dc2626;
        }

        .panel-label.sahi {
          background: #f3f0ff;
          color: #7C3AED;
        }

        .panel-title {
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 20px;
          font-weight: 700;
          color: #0f172a;
          margin: 0 0 24px 0;
        }

        /* Mock UI cards inside panels */
        .mock-card {
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 12px;
          padding: 16px;
          margin-bottom: 16px;
        }

        .mock-card.legacy-card {
          border-color: #fecaca;
          background: #fff5f5;
        }

        .mock-card.sahi-card {
          border-color: #ddd6fe;
          background: #faf5ff;
        }

        .mock-tag {
          display: inline-flex;
          align-items: center;
          gap: 4px;
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 11px;
          font-weight: 600;
          padding: 3px 10px;
          border-radius: 100px;
          margin-bottom: 8px;
        }

        .mock-tag.red {
          background: #fee2e2;
          color: #dc2626;
        }

        .mock-tag.purple {
          background: #ede9fe;
          color: #7C3AED;
        }

        .mock-card-text {
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 13px;
          color: #475569;
          line-height: 1.5;
          margin: 0;
        }

        .mock-score-row {
          display: flex;
          align-items: center;
          justify-content: space-between;
          margin-top: 10px;
        }

        .mock-score-bar-track {
          flex: 1;
          height: 6px;
          background: #f1f5f9;
          border-radius: 3px;
          margin: 0 10px;
          overflow: hidden;
        }

        .mock-score-bar-fill {
          height: 100%;
          border-radius: 3px;
        }

        .mock-score-label {
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 11px;
          font-weight: 700;
          color: #0f172a;
          min-width: 32px;
          text-align: right;
        }

        /* Point lists */
        .points-list {
          list-style: none;
          padding: 0;
          margin: 0;
        }

        .points-list li {
          display: flex;
          align-items: flex-start;
          gap: 10px;
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 14px;
          color: #475569;
          line-height: 1.55;
          padding: 8px 0;
          border-bottom: 1px solid #f1f5f9;
        }

        .points-list li:last-child {
          border-bottom: none;
        }

        .point-icon {
          width: 20px;
          height: 20px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          flex-shrink: 0;
          margin-top: 1px;
        }

        .point-icon.bad {
          background: #fee2e2;
        }

        .point-icon.good {
          background: #f0fdf4;
        }

        /* VS divider */
        .vs-divider {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 0 8px;
          position: relative;
        }

        .vs-badge {
          background: #0f172a;
          color: white;
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 13px;
          font-weight: 800;
          width: 44px;
          height: 44px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          letter-spacing: 0.5px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.15);
          z-index: 2;
          position: relative;
        }

        .vs-line {
          position: absolute;
          top: 0;
          bottom: 0;
          width: 1px;
          background: linear-gradient(to bottom, transparent, #e2e8f0 20%, #e2e8f0 80%, transparent);
        }

        /* SahiScreen Panel */
        .panel-sahi {
          padding: 36px 32px;
          background: #ffffff;
        }

        /* Feature bullets below */
        .feature-bullets {
          display: flex;
          flex-direction: column;
          gap: 14px;
        }

        .feature-bullet {
          display: flex;
          align-items: center;
          gap: 14px;
          padding: 14px 18px;
          background: white;
          border: 1px solid #f1f5f9;
          border-radius: 12px;
          transition: all 0.2s ease;
        }

        .feature-bullet:hover {
          border-color: #ddd6fe;
          box-shadow: 0 4px 16px rgba(124,58,237,0.08);
          transform: translateX(4px);
        }

        .feature-bullet-icon {
          width: 40px;
          height: 40px;
          border-radius: 10px;
          display: flex;
          align-items: center;
          justify-content: center;
          flex-shrink: 0;
        }

        .feature-bullet-text {
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 14px;
          font-weight: 500;
          color: #334155;
          line-height: 1.5;
        }

        @media (max-width: 1024px) {
          .comparison-title { font-size: 30px; }
          .comparison-title .line1 { font-size: 18px; }
          .panel-legacy, .panel-sahi { padding: 28px 20px; }
        }

        @media (max-width: 768px) {
          .comparison-section { padding: 72px 24px; }
          .comparison-grid {
            grid-template-columns: 1fr;
          }
          .vs-divider {
            flex-direction: row;
            padding: 12px 24px;
            border-top: 1px solid #e2e8f0;
            border-bottom: 1px solid #e2e8f0;
            background: #f8fafc;
          }
          .vs-line {
            top: 50%;
            bottom: auto;
            left: 0;
            right: 0;
            width: auto;
            height: 1px;
            background: linear-gradient(to right, transparent, #e2e8f0 20%, #e2e8f0 80%, transparent);
          }
          .panel-legacy {
            border-right: none;
            border-bottom: none;
          }
          .comparison-title { font-size: 26px; }
          .comparison-title .line1 { font-size: 16px; }
        }

        @media (max-width: 480px) {
          .comparison-header { margin-bottom: 36px; }
        }
      `}</style>

      <section className="comparison-section" id="ai-tech">
        <div className="comparison-bg" />
        <div className="comparison-inner">
          {/* Header */}
          <div className="comparison-header">
            <h2 className="comparison-title">
              <span className="line1">Stop Keyword Matching.</span>
              <span className="line2">
                Start{" "}
                <span className="highlight">Contextual Understanding.</span>
              </span>
            </h2>
          </div>

          {/* Comparison Grid */}
          <div className="comparison-grid">
            {/* Legacy ATS */}
            <div className="panel-legacy">
              <span className="panel-label legacy">
                <X size={10} strokeWidth={3} /> Legacy ATS
              </span>

              {/* Mock legacy card */}
              <div className="mock-card legacy-card">
                <div className="mock-tag red">
                  <X size={9} strokeWidth={3} /> KEYWORD MATCH
                </div>
                <p className="mock-card-text">
                  "Project Lead" found 3 times — candidate ranked high
                </p>
                <div className="mock-score-row">
                  <span
                    style={{
                      fontSize: 11,
                      color: "#94a3b8",
                      fontFamily: "Plus Jakarta Sans, sans-serif",
                    }}
                  >
                    Score
                  </span>
                  <div className="mock-score-bar-track">
                    <div
                      className="mock-score-bar-fill"
                      style={{ width: "82%", background: "#fca5a5" }}
                    />
                  </div>
                  <span className="mock-score-label">82%</span>
                </div>
              </div>

              <ul className="points-list">
                {legacyPoints.map((pt) => (
                  <li key={pt}>
                    <span className="point-icon bad">
                      <X size={11} color="#dc2626" strokeWidth={3} />
                    </span>
                    {pt}
                  </li>
                ))}
              </ul>
            </div>

            {/* VS */}
            <div className="vs-divider">
              <div className="vs-line" />
              <div className="vs-badge">VS</div>
            </div>

            {/* SahiScreen */}
            <div className="panel-sahi">
              <span className="panel-label sahi">
                <Check size={10} strokeWidth={3} /> SahiScreen AI
              </span>

              {/* Mock sahi card */}
              <div className="mock-card sahi-card">
                <div className="mock-tag purple">
                  <Check size={9} strokeWidth={3} /> CONTEXTUAL REASONING
                </div>
                <p className="mock-card-text">
                  Candidate led 3 cross-functional projects — genuine leadership
                  depth detected
                </p>
                <div className="mock-score-row">
                  <span
                    style={{
                      fontSize: 11,
                      color: "#94a3b8",
                      fontFamily: "Plus Jakarta Sans, sans-serif",
                    }}
                  >
                    Score
                  </span>
                  <div className="mock-score-bar-track">
                    <div
                      className="mock-score-bar-fill"
                      style={{
                        width: "94%",
                        background: "linear-gradient(90deg, #7C3AED, #a78bfa)",
                      }}
                    />
                  </div>
                  <span className="mock-score-label">94%</span>
                </div>
              </div>

              <ul className="points-list">
                {sahiPoints.map((pt) => (
                  <li key={pt}>
                    <span className="point-icon good">
                      <Check size={11} color="#16a34a" strokeWidth={3} />
                    </span>
                    {pt}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Feature Bullets */}
          <div className="feature-bullets">
            {featureBullets.map((fb) => {
              const Icon = fb.icon;
              return (
                <div className="feature-bullet" key={fb.text}>
                  <div
                    className="feature-bullet-icon"
                    style={{ background: fb.bg }}
                  >
                    <Icon
                      size={18}
                      style={{ color: fb.color }}
                      strokeWidth={1.8}
                    />
                  </div>
                  <span className="feature-bullet-text">{fb.text}</span>
                </div>
              );
            })}
          </div>
        </div>
      </section>
    </>
  );
}
